### ISSUE TITLE
make quickstart-dev failed

### ISSUE THREAD

**Issue by lmcl90** [ory/kratos#965] opened 2021-01-06 13:38 UTC
Here is the execution log for `make quickstart-dev`

```
➜  kratos git:(import_credentials) ✗ make quickstart-dev
docker build -f .docker/Dockerfile-build -t oryd/kratos:latest-sqlite .
Sending build context to Docker daemon  3.906MB
Step 1/21 : FROM golang:1.15-alpine AS builder
 ---> 1463476d8605
Step 2/21 : RUN apk -U --no-cache add build-base git gcc bash
 ---> Using cache
 ---> b5f6ba8c8e74
Step 3/21 : WORKDIR /go/src/github.com/ory/kratos
 ---> Using cache
 ---> 93f3d6bf5eff
Step 4/21 : ADD go.mod go.mod
 ---> ef14ce7121f6
Step 5/21 : ADD go.sum go.sum
 ---> f68f79dd036e
Step 6/21 : ENV GO111MODULE on
 ---> Running in 16adbf6babd1
Removing intermediate container 16adbf6babd1
 ---> 2dbcdbf2933c
Step 7/21 : ENV CGO_ENABLED 1
 ---> Running in 22e69959bb7f
Removing intermediate container 22e69959bb7f
 ---> 23ffa2841744
Step 8/21 : RUN go mod download
 ---> Running in 17edefb976cb
go: github.com/ory/kratos-client-go@v0.5.4-alpha.1: parsing internal/httpclient/go.mod: open /go/src/github.com/ory/kratos/internal/httpclient/go.mod: no such file or directory
The command '/bin/sh -c go mod download' returned a non-zero code: 1
make: *** [quickstart-dev] Error 1
```

This [`line`](https://github.com/ory/kratos/blob/master/go.mod#L12) in go.mod will let the download procedure find the client module in local, but it add all source code files after `RUN go mod download` in [Dockerfile-build](https://github.com/ory/kratos/blob/master/.docker/Dockerfile-build#L15).

**Comment by aeneasr** [comment] 2021-01-08 08:23
This is caused by the same thing explained here: https://github.com/ory/kratos/issues/950

Closing as a duplicate!

**Comment by lmcl90** [comment] 2021-01-12 03:56
> This is caused by the same thing explained here: #950
> 
> Closing as a duplicate!

I just tested this on the lastest master branch which already fixed #950, but the problem still occured. @aeneasr 

The root casue is because it doesn't provide `internal/httpclient/go.mod` to dockerfile before executing `go mod download`。

**Comment by aeneasr** [comment] 2021-01-12 09:02
Ah, thank you - would you be open to submit a PR for that?

**Comment by lmcl90** [comment] 2021-01-12 09:45
Yes, I'll fix this.

**Closed** 2021-01-13 12:41 UTC
Labels: corp/m4
