### ISSUE TITLE
Quickstart not working in tag:v0.4.6-alpha.1

### ISSUE THREAD

**Issue by cdreier** [ory/kratos#575] opened 2020-07-14 15:28 UTC
**Describe the bug**

i tried to walk through the quickstart docs, but ended with an error when trying to connect to the secured dashboard

**Reproducing the bug**

1. successfully executed everything from https://www.ory.sh/kratos/docs/quickstart#clone-ory-kratos-and-run-it-in-docker
2. opened http://127.0.0.1:4455/dashboard in the browser

_Server logs_

```
kratos-selfservice-ui-node_1  | GET /dashboard 302 66 - 1010.557 ms
kratos-selfservice-ui-node_1  | No request found in URL, initializing auth flow.
kratos-selfservice-ui-node_1  | GET /auth/login 302 148 - 2.597 ms
kratos-selfservice-ui-node_1  | Error: connect EHOSTUNREACH 172.20.0.5:4433
kratos-selfservice-ui-node_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
kratos-selfservice-ui-node_1  | GET /.ory/kratos/public/self-service/browser/flows/login 500 11460 - 1088.939 ms
kratos-selfservice-ui-node_1  | GET /index.css 304 - - 1.120 ms
kratos-selfservice-ui-node_1  | GET /typography.css 304 - - 1.176 ms
kratos-selfservice-ui-node_1  | GET /form.css 304 - - 1.173 ms
kratos-selfservice-ui-node_1  | GET /auth.css 304 - - 0.360 ms
kratos-selfservice-ui-node_1  | GET /favicon.ico 302 22 - 0.549 ms

```

**Expected behavior**

as described, expected to get redirected to a login page

**Environment**

- Version: tag:v0.4.6-alpha.1
- Environment: fedora, docker, docker-compose

**Additional context**

ended up in the browser http://127.0.0.1:4455/.ory/kratos/public/self-service/browser/flows/login

![image](https://user-images.githubusercontent.com/731608/87444662-5ad93600-c5f7-11ea-8b4b-342890bc642d.png)

**Comment by aeneasr** [comment] 2020-07-15 09:56
I tried to reproduce this but couldn't could you maybe share the following to help debug:

```
$ docker ps
$ docker-compose -f quickstart.yml logs

**Comment by cdreier** [comment] 2020-07-15 13:15
Hi, thanks for your response!

docker ps is empty, no containers are running.

output from docker-compose logs is

```(tag:v0.4.6-alpha.1 ✓) kratos docker-compose -f quickstart.yml logs
Attaching to kratos_kratos_1, kratos_kratos-selfservice-ui-node_1, kratos_mailslurper_1, kratos_kratos-migrate_1
kratos-migrate_1              | time=2020-07-14T15:13:12Z level=info msg=Config file loaded successfully. audience=application path=/etc/config/kratos/.kratos.yml service_name=kratos service_version=
kratos-migrate_1              | [POP] 2020/07/14 15:13:12 warn - ignoring file .gitignore because it does not match the migration file pattern
kratos-migrate_1              | The following migration is planned:
kratos-migrate_1              | 
kratos-migrate_1              | Version          Name                           Status    
kratos-migrate_1              | 20191100000001   identities                     Pending   
kratos-migrate_1              | 20191100000001   identities                     Pending   
kratos-migrate_1              | 20191100000001   identities                     Pending   
kratos-migrate_1              | 20191100000001   identities                     Pending   
kratos-migrate_1              | 20191100000002   requests                       Pending   
kratos-migrate_1              | 20191100000002   requests                       Pending   
kratos-migrate_1              | 20191100000002   requests                       Pending   
kratos-migrate_1              | 20191100000002   requests                       Pending   
kratos-migrate_1              | 20191100000003   sessions                       Pending   
kratos-migrate_1              | 20191100000003   sessions                       Pending   
kratos-migrate_1              | 20191100000003   sessions                       Pending   
kratos-migrate_1              | 20191100000003   sessions                       Pending   
kratos-migrate_1              | 20191100000004   errors                         Pending   
kratos-migrate_1              | 20191100000004   errors                         Pending   
kratos-migrate_1              | 20191100000004   errors                         Pending   
kratos-migrate_1              | 20191100000004   errors                         Pending   
kratos-migrate_1              | 20191100000005   identities                     Pending   
kratos-migrate_1              | 20191100000006   courier                        Pending   
kratos-migrate_1              | 20191100000006   courier                        Pending   
kratos-migrate_1              | 20191100000006   courier                        Pending   
kratos-migrate_1              | 20191100000006   courier                        Pending   
kratos-migrate_1              | 20191100000007   errors                         Pending   
kratos-migrate_1              | 20191100000007   errors                         Pending   
kratos-migrate_1              | 20191100000007   errors                         Pending   
kratos-migrate_1              | 20191100000007   errors                         Pending   
kratos-migrate_1              | 20191100000008   selfservice_verification       Pending   
kratos-migrate_1              | 20191100000008   selfservice_verification       Pending   
kratos-migrate_1              | 20191100000008   selfservice_verification       Pending   
kratos-migrate_1              | 20191100000008   selfservice_verification       Pending   
kratos-migrate_1              | 20191100000009   verification                   Pending   
kratos-migrate_1              | 20191100000010   errors                         Pending   
kratos-migrate_1              | 20191100000010   errors                         Pending   
kratos-migrate_1              | 20191100000010   errors                         Pending   
kratos-migrate_1              | 20191100000010   errors                         Pending   
kratos-migrate_1              | 20191100000011   courier_body_type              Pending   
kratos-migrate_1              | 20191100000011   courier_body_type              Pending   
kratos-migrate_1              | 20191100000011   courier_body_type              Pending   
kratos-migrate_1              | 20191100000011   courier_body_type              Pending   
kratos-migrate_1              | 20191100000012   login_request_forced           Pending   
kratos-migrate_1              | 20191100000012   login_request_forced           Pending   
kratos-migrate_1              | 20191100000012   login_request_forced           Pending   
kratos-migrate_1              | 20191100000012   login_request_forced           Pending   
kratos-migrate_1              | 20200317160354   create_profile_request_forms   Pending   
kratos-migrate_1              | 20200317160354   create_profile_request_forms   Pending   
kratos-migrate_1              | 20200317160354   create_profile_request_forms   Pending   
kratos-migrate_1              | 20200317160354   create_profile_request_forms   Pending   
kratos-migrate_1              | 20200401183443   continuity_containers          Pending   
kratos-migrate_1              | 20200401183443   continuity_containers          Pending   
kratos-migrate_1              | 20200401183443   continuity_containers          Pending   
kratos-migrate_1              | 20200401183443   continuity_containers          Pending   
kratos-migrate_1              | 20200402142539   rename_profile_flows           Pending   
kratos-migrate_1              | 20200402142539   rename_profile_flows           Pending   
kratos-migrate_1              | 20200402142539   rename_profile_flows           Pending   
kratos-migrate_1              | 20200402142539   rename_profile_flows           Pending   
kratos-migrate_1              | 20200519101057   create_recovery_addresses      Pending   
kratos-migrate_1              | 20200519101057   create_recovery_addresses      Pending   
kratos-migrate_1              | 20200519101057   create_recovery_addresses      Pending   
kratos-migrate_1              | 20200519101057   create_recovery_addresses      Pending   
kratos-migrate_1              | 20200519101058   create_recovery_addresses      Pending   
kratos-migrate_1              | 20200601101000   create_messages                Pending   
kratos-migrate_1              | 20200601101000   create_messages                Pending   
kratos-migrate_1              | 20200601101000   create_messages                Pending   
kratos-migrate_1              | 20200601101000   create_messages                Pending   
kratos-migrate_1              | 20200601101001   verification                   Pending   
kratos-migrate_1              | 20200605111551   messages                       Pending   
kratos-migrate_1              | 20200605111551   messages                       Pending   
kratos-migrate_1              | 20200605111551   messages                       Pending   
kratos-migrate_1              | 20200605111551   messages                       Pending   
kratos-migrate_1              | 20200607165100   settings                       Pending   
kratos-migrate_1              | 20200607165100   settings                       Pending   
kratos-migrate_1              | 20200607165100   settings                       Pending   
kratos-migrate_1              | 20200607165100   settings                       Pending   
kratos-migrate_1              | 20200705105359   rename_identities_schema       Pending   
kratos-migrate_1              | 20200705105359   rename_identities_schema       Pending   
kratos-migrate_1              | 20200705105359   rename_identities_schema       Pending   
kratos-migrate_1              | 20200705105359   rename_identities_schema       Pending   
kratos-migrate_1              | [POP] 2020/07/14 15:13:12 info - > identities
kratos-migrate_1              | [POP] 2020/07/14 15:13:12 info - > requests
kratos-migrate_1              | [POP] 2020/07/14 15:13:12 info - > sessions
kratos-migrate_1              | [POP] 2020/07/14 15:13:12 info - > errors
kratos-migrate_1              | [POP] 2020/07/14 15:13:12 info - > courier
kratos-migrate_1              | [POP] 2020/07/14 15:13:12 info - > errors
kratos-migrate_1              | [POP] 2020/07/14 15:13:12 info - > selfservice_verification
kratos-migrate_1              | [POP] 2020/07/14 15:13:12 info - > errors
kratos-migrate_1              | [POP] 2020/07/14 15:13:12 info - > courier_body_type
kratos-migrate_1              | [POP] 2020/07/14 15:13:12 info - > login_request_forced
kratos-migrate_1              | [POP] 2020/07/14 15:13:12 info - > create_profile_request_forms
kratos-migrate_1              | [POP] 2020/07/14 15:13:12 info - > continuity_containers
kratos-migrate_1              | [POP] 2020/07/14 15:13:12 info - > rename_profile_flows
kratos-migrate_1              | [POP] 2020/07/14 15:13:12 info - > create_recovery_addresses
kratos-migrate_1              | [POP] 2020/07/14 15:13:12 info - > create_messages
kratos-migrate_1              | [POP] 2020/07/14 15:13:12 info - > messages
kratos-migrate_1              | [POP] 2020/07/14 15:13:12 info - > settings
kratos-migrate_1              | [POP] 2020/07/14 15:13:12 info - > rename_identities_schema
kratos-migrate_1              | [POP] 2020/07/14 15:13:12 info - Successfully applied 18 migrations.
kratos-migrate_1              | [POP] 2020/07/14 15:13:12 info - 0.0901 seconds
kratos-migrate_1              | Successfully applied SQL migrations!
kratos-selfservice-ui-node_1  | 
kratos-selfservice-ui-node_1  | > kratos-selfservice-ui-node@0.0.1 serve /usr/src/app
kratos-selfservice-ui-node_1  | > node lib/index.js
kratos-selfservice-ui-node_1  | 
kratos-selfservice-ui-node_1  | Listening on http://0.0.0.0:4455
kratos-selfservice-ui-node_1  | Security mode: cookie
kratos-selfservice-ui-node_1  | GET /dashboard 302 66 - 1038.268 ms
kratos-selfservice-ui-node_1  | No request found in URL, initializing auth flow.
kratos-selfservice-ui-node_1  | GET /auth/login 302 148 - 3.399 ms
kratos-selfservice-ui-node_1  | Error: connect EHOSTUNREACH 172.20.0.5:4433
kratos-selfservice-ui-node_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
kratos-selfservice-ui-node_1  | GET /.ory/kratos/public/self-service/browser/flows/login 500 11460 - 1103.293 ms
kratos-selfservice-ui-node_1  | GET /index.css 200 3479 - 6.348 ms
kratos-selfservice-ui-node_1  | GET /typography.css 200 819 - 9.978 ms
kratos-selfservice-ui-node_1  | GET /auth.css 200 556 - 10.084 ms
kratos-selfservice-ui-node_1  | GET /form.css 200 2201 - 11.507 ms
kratos-selfservice-ui-node_1  | GET /favicon.ico 302 22 - 1.513 ms
kratos-selfservice-ui-node_1  | GET /index.css 304 - - 3.647 ms
kratos-selfservice-ui-node_1  | GET /typography.css 304 - - 3.871 ms
kratos-selfservice-ui-node_1  | GET /form.css 304 - - 3.573 ms
kratos-selfservice-ui-node_1  | GET /auth.css 304 - - 2.970 ms
kratos-selfservice-ui-node_1  | GET /dashboard 302 66 - 1011.253 ms
kratos-selfservice-ui-node_1  | No request found in URL, initializing auth flow.
kratos-selfservice-ui-node_1  | GET /auth/login 302 148 - 1.306 ms
kratos-selfservice-ui-node_1  | Error: connect EHOSTUNREACH 172.20.0.5:4433
kratos-selfservice-ui-node_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
kratos-selfservice-ui-node_1  | GET /.ory/kratos/public/self-service/browser/flows/login 500 11460 - 1049.545 ms
kratos-selfservice-ui-node_1  | GET /index.css 200 3479 - 0.706 ms
kratos-selfservice-ui-node_1  | GET /typography.css 200 819 - 1.667 ms
kratos-selfservice-ui-node_1  | GET /form.css 200 2201 - 0.943 ms
kratos-selfservice-ui-node_1  | GET /auth.css 200 556 - 0.905 ms
kratos-selfservice-ui-node_1  | GET /favicon.ico 302 22 - 0.884 ms
kratos-selfservice-ui-node_1  | GET /dashboard 302 66 - 1020.727 ms
kratos-selfservice-ui-node_1  | No request found in URL, initializing auth flow.
kratos-selfservice-ui-node_1  | GET /auth/login 302 148 - 2.449 ms
kratos-selfservice-ui-node_1  | Error: connect EHOSTUNREACH 172.20.0.5:4433
kratos-selfservice-ui-node_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
kratos-selfservice-ui-node_1  | GET /.ory/kratos/public/self-service/browser/flows/login 500 11460 - 1107.704 ms
kratos-selfservice-ui-node_1  | GET /index.css 200 3479 - 3.745 ms
kratos-selfservice-ui-node_1  | GET /typography.css 200 819 - 4.104 ms
kratos-selfservice-ui-node_1  | GET /form.css 200 2201 - 4.325 ms
kratos-selfservice-ui-node_1  | GET /auth.css 200 556 - 4.675 ms
kratos-selfservice-ui-node_1  | GET /favicon.ico 302 22 - 0.698 ms
kratos-selfservice-ui-node_1  | GET /favicon.ico 302 22 - 0.651 ms
kratos-selfservice-ui-node_1  | Error: connect EHOSTUNREACH 172.20.0.5:4433
kratos-selfservice-ui-node_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
kratos-selfservice-ui-node_1  | GET /.ory/kratos/public/self-service/browser/flows/login 500 11460 - 1072.855 ms
kratos-selfservice-ui-node_1  | GET /index.css 200 3479 - 2.716 ms
kratos-selfservice-ui-node_1  | GET /typography.css 200 819 - 2.406 ms
kratos-selfservice-ui-node_1  | GET /form.css 200 2201 - 2.532 ms
kratos-selfservice-ui-node_1  | GET /auth.css 200 556 - 2.923 ms
kratos-selfservice-ui-node_1  | GET /favicon.ico 302 22 - 0.970 ms
kratos-selfservice-ui-node_1  | GET /dashboard 302 66 - 1068.176 ms
kratos-selfservice-ui-node_1  | No request found in URL, initializing auth flow.
kratos-selfservice-ui-node_1  | GET /auth/login 302 148 - 2.552 ms
kratos-selfservice-ui-node_1  | Error: connect EHOSTUNREACH 172.20.0.5:4433
kratos-selfservice-ui-node_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
kratos-selfservice-ui-node_1  | GET /.ory/kratos/public/self-service/browser/flows/login 500 11460 - 1106.137 ms
kratos-selfservice-ui-node_1  | GET /index.css 304 - - 1.105 ms
kratos-selfservice-ui-node_1  | GET /typography.css 304 - - 1.057 ms
kratos-selfservice-ui-node_1  | GET /form.css 304 - - 0.672 ms
kratos-selfservice-ui-node_1  | GET /auth.css 304 - - 0.439 ms
kratos-selfservice-ui-node_1  | GET /favicon.ico 302 22 - 0.603 ms
kratos-selfservice-ui-node_1  | GET /dashboard 302 66 - 1010.557 ms
kratos-selfservice-ui-node_1  | No request found in URL, initializing auth flow.
kratos-selfservice-ui-node_1  | GET /auth/login 302 148 - 2.597 ms
kratos-selfservice-ui-node_1  | Error: connect EHOSTUNREACH 172.20.0.5:4433
kratos-selfservice-ui-node_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
kratos-selfservice-ui-node_1  | GET /.ory/kratos/public/self-service/browser/flows/login 500 11460 - 1088.939 ms
kratos-selfservice-ui-node_1  | GET /index.css 304 - - 1.120 ms
kratos-selfservice-ui-node_1  | GET /typography.css 304 - - 1.176 ms
kratos-selfservice-ui-node_1  | GET /form.css 304 - - 1.173 ms
kratos-selfservice-ui-node_1  | GET /auth.css 304 - - 0.360 ms
kratos-selfservice-ui-node_1  | GET /favicon.ico 302 22 - 0.549 ms
mailslurper_1                 | time="2020-07-14T15:13:12Z" level=info msg="Starting MailSlurper Server v1.14.1" who=MailSlurper
mailslurper_1                 | time="2020-07-14T15:13:12Z" level=info msg="Connecting to database" who=MailSlurper
mailslurper_1                 | time="2020-07-14T15:13:12Z" level=info msg="Creating database tables..." who=MailSlurper
mailslurper_1                 | time="2020-07-14T15:13:12Z" level=info msg="Created tables successfully." who=MailSlurper
mailslurper_1                 | time="2020-07-14T15:13:12Z" level=info msg="Worker pool configured for 1000 workers" who="SMTP Server Pool"
mailslurper_1                 | time="2020-07-14T15:13:12Z" level=info msg="SMTP listener running on SSL 0.0.0.0:1025" who="SMTP Listener"
mailslurper_1                 | time="2020-07-14T15:13:12Z" level=info msg="1 receiver(s) listening" who="SMTP Listener"
mailslurper_1                 | ⇨ http server started on [::]:4436
mailslurper_1                 | ⇨ http server started on [::]:4437
mailslurper_1                 | time="2020-07-14T15:13:12Z" level=info msg="HTTP admin listener running on 0.0.0.0:4436" who=MailSlurper
mailslurper_1                 | time="2020-07-14T15:28:22Z" level=info msg="Shutting down receiver channel..." who="SMTP Listener"
mailslurper_1                 | time="2020-07-14T15:28:22Z" level=info msg="Shutting down receiver channel..." who="SMTP Listener"
mailslurper_1                 | time="2020-07-14T15:28:22Z" level=info msg="Shutting down receiver channel..." who="SMTP Listener"
mailslurper_1                 | time="2020-07-14T15:28:22Z" level=info msg="Shutting down receiver channel..." who="SMTP Listener"
mailslurper_1                 | time="2020-07-14T15:28:22Z" level=info msg="Shutting down receiver channel..." who="SMTP Listener"
kratos_1                      | time=2020-07-14T15:13:13Z level=info msg=Config file loaded successfully. audience=application path=/etc/config/kratos/.kratos.yml service_name=kratos service_version=
kratos_1                      | time=2020-07-14T15:13:13Z level=warning msg=
kratos_1                      | 
kratos_1                      | YOU ARE RUNNING ORY KRATOS IN DEV MODE.
kratos_1                      | SECURITY IS DISABLED.
kratos_1                      | DON'T DO THIS IN PRODUCTION!
kratos_1                      | 
kratos_1                      |  audience=application service_name=kratos service_version=
kratos_1                      | [POP] 2020/07/14 15:13:13 warn - ignoring file .gitignore because it does not match the migration file pattern
kratos_1                      | time=2020-07-14T15:13:13Z level=info msg=Courier worker started. audience=application service_name=kratos service_version=
kratos_1                      | time=2020-07-14T15:13:13Z level=info msg=Software quality assurance features are enabled. Learn more at: https://www.ory.sh/docs/ecosystem/sqa audience=application service_name=kratos service_version=
kratos_1                      | time=2020-07-14T15:13:13Z level=info msg=Starting the admin httpd on: 0.0.0.0:4434 audience=application service_name=kratos service_version=
kratos_1                      | time=2020-07-14T15:13:13Z level=info msg=Starting the public httpd on: 0.0.0.0:4433 audience=application service_name=kratos service_version=
kratos_1                      | time=2020-07-14T15:16:58Z level=info msg=started handling request method=GET name=admin#http://kratos:4434/ remote=172.20.0.1:47562 request=/
kratos_1                      | time=2020-07-14T15:16:58Z level=info msg=completed handling request method=GET name=admin#http://kratos:4434/ remote=172.20.0.1:47562 request=/ status=404 text_status=Not Found took=429.713µs
kratos_1                      | time=2020-07-14T15:16:58Z level=info msg=started handling request method=GET name=admin#http://kratos:4434/ remote=172.20.0.1:47562 request=/favicon.ico
kratos_1                      | time=2020-07-14T15:16:58Z level=info msg=completed handling request method=GET name=admin#http://kratos:4434/ remote=172.20.0.1:47562 request=/favicon.ico status=404 text_status=Not Found took=61.411µs
kratos_1                      | time=2020-07-14T15:28:22Z level=info msg=Courier worker was shutdown gracefully. audience=application service_name=kratos service_version=
kratos_1                      | time=2020-07-14T15:28:22Z level=info msg=Admin httpd was shutdown gracefully audience=application service_name=kratos service_version=
kratos_1                      | time=2020-07-14T15:28:22Z level=info msg=Public httpd was shutdown gracefully audience=application service_name=kratos service_version=
```

one additional note, i had a few problems with docker on fedora 32, as some changes caused problems with resolving DNS

https://ask.fedoraproject.org/t/dns-resolution-errors-with-docker-in-fedora-32/6385/3

this should only be a problem when communicating out of the docker internal networks to the world, but noone knows all the side effects, so perhaps this info helps :)

**Comment by aeneasr** [comment] 2020-07-15 13:21
If `docker ps` is empty, then no container is running, which probably explains your issues?

**Comment by cdreier** [comment] 2020-07-16 06:19
hi, thanks a lot for your help again, but i shut down the compose containers, i thought you want to check if any other services are running :) 

when everything is started, the output is

```
42d55a020c8d        oryd/kratos:latest-sqlite                "kratos serve -c /et…"   6 seconds ago       Up 5 seconds        0.0.0.0:4433-4434->4433-4434/tcp                                 kratos_kratos_1
e20915b0e13c        oryd/kratos-selfservice-ui-node:latest   "/bin/sh -c 'npm run…"   7 seconds ago       Up 6 seconds        3000/tcp, 0.0.0.0:4455->4455/tcp                                 kratos_kratos-selfservice-ui-node_1
169e4bdca013        oryd/mailslurper:latest-smtps            "./mailslurper"          7 seconds ago       Up 6 seconds        2500/tcp, 8080/tcp, 8085/tcp, 0.0.0.0:4436-4437->4436-4437/tcp   kratos_mailslurper_1
```

startup logs as seen above

```
(tag:v0.4.6-alpha.1 ✓) kratos docker-compose -f quickstart.yml -f quickstart-standalone.yml up --build --force-recreate 
Recreating kratos_mailslurper_1                ... done
Recreating kratos_kratos-selfservice-ui-node_1 ... done
Recreating kratos_kratos-migrate_1             ... done
Recreating kratos_kratos_1                     ... done
Attaching to kratos_kratos-migrate_1, kratos_kratos-selfservice-ui-node_1, kratos_mailslurper_1, kratos_kratos_1
kratos-migrate_1              | time=2020-07-16T06:16:06Z level=info msg=Config file loaded successfully. audience=application path=/etc/config/kratos/.kratos.yml service_name=kratos service_version=
kratos-migrate_1              | [POP] 2020/07/16 06:16:06 warn - ignoring file .gitignore because it does not match the migration file pattern
kratos-migrate_1              | The following migration is planned:
kratos-migrate_1              | 
kratos-migrate_1              | Version          Name                           Status    
kratos-migrate_1              | 20191100000001   identities                     Applied   
kratos-migrate_1              | 20191100000001   identities                     Applied   
kratos-migrate_1              | 20191100000001   identities                     Applied   
kratos-migrate_1              | 20191100000001   identities                     Applied   
kratos-migrate_1              | 20191100000002   requests                       Applied   
kratos-migrate_1              | 20191100000002   requests                       Applied   
kratos-migrate_1              | 20191100000002   requests                       Applied   
kratos-migrate_1              | 20191100000002   requests                       Applied   
kratos-migrate_1              | 20191100000003   sessions                       Applied   
kratos-migrate_1              | 20191100000003   sessions                       Applied   
kratos-migrate_1              | 20191100000003   sessions                       Applied   
kratos-migrate_1              | 20191100000003   sessions                       Applied   
kratos-migrate_1              | 20191100000004   errors                         Applied   
kratos-migrate_1              | 20191100000004   errors                         Applied   
kratos-migrate_1              | 20191100000004   errors                         Applied   
kratos-migrate_1              | 20191100000004   errors                         Applied   
kratos-migrate_1              | 20191100000005   identities                     Pending   
kratos-migrate_1              | 20191100000006   courier                        Applied   
kratos-migrate_1              | 20191100000006   courier                        Applied   
kratos-migrate_1              | 20191100000006   courier                        Applied   
kratos-migrate_1              | 20191100000006   courier                        Applied   
kratos-migrate_1              | 20191100000007   errors                         Applied   
kratos-migrate_1              | 20191100000007   errors                         Applied   
kratos-migrate_1              | 20191100000007   errors                         Applied   
kratos-migrate_1              | 20191100000007   errors                         Applied   
kratos-migrate_1              | 20191100000008   selfservice_verification       Applied   
kratos-migrate_1              | 20191100000008   selfservice_verification       Applied   
kratos-migrate_1              | 20191100000008   selfservice_verification       Applied   
kratos-migrate_1              | 20191100000008   selfservice_verification       Applied   
kratos-migrate_1              | 20191100000009   verification                   Pending   
kratos-migrate_1              | 20191100000010   errors                         Applied   
kratos-migrate_1              | 20191100000010   errors                         Applied   
kratos-migrate_1              | 20191100000010   errors                         Applied   
kratos-migrate_1              | 20191100000010   errors                         Applied   
kratos-migrate_1              | 20191100000011   courier_body_type              Applied   
kratos-migrate_1              | 20191100000011   courier_body_type              Applied   
kratos-migrate_1              | 20191100000011   courier_body_type              Applied   
kratos-migrate_1              | 20191100000011   courier_body_type              Applied   
kratos-migrate_1              | 20191100000012   login_request_forced           Applied   
kratos-migrate_1              | 20191100000012   login_request_forced           Applied   
kratos-migrate_1              | 20191100000012   login_request_forced           Applied   
kratos-migrate_1              | 20191100000012   login_request_forced           Applied   
kratos-migrate_1              | 20200317160354   create_profile_request_forms   Applied   
kratos-migrate_1              | 20200317160354   create_profile_request_forms   Applied   
kratos-migrate_1              | 20200317160354   create_profile_request_forms   Applied   
kratos-migrate_1              | 20200317160354   create_profile_request_forms   Applied   
kratos-migrate_1              | 20200401183443   continuity_containers          Applied   
kratos-migrate_1              | 20200401183443   continuity_containers          Applied   
kratos-migrate_1              | 20200401183443   continuity_containers          Applied   
kratos-migrate_1              | 20200401183443   continuity_containers          Applied   
kratos-migrate_1              | 20200402142539   rename_profile_flows           Applied   
kratos-migrate_1              | 20200402142539   rename_profile_flows           Applied   
kratos-migrate_1              | 20200402142539   rename_profile_flows           Applied   
kratos-migrate_1              | 20200402142539   rename_profile_flows           Applied   
kratos-migrate_1              | 20200519101057   create_recovery_addresses      Applied   
kratos-migrate_1              | 20200519101057   create_recovery_addresses      Applied   
kratos-migrate_1              | 20200519101057   create_recovery_addresses      Applied   
kratos-migrate_1              | 20200519101057   create_recovery_addresses      Applied   
kratos-migrate_1              | 20200519101058   create_recovery_addresses      Pending   
kratos-migrate_1              | 20200601101000   create_messages                Applied   
kratos-migrate_1              | 20200601101000   create_messages                Applied   
kratos-migrate_1              | 20200601101000   create_messages                Applied   
kratos-migrate_1              | 20200601101000   create_messages                Applied   
kratos-migrate_1              | 20200601101001   verification                   Pending   
kratos-migrate_1              | 20200605111551   messages                       Applied   
kratos-migrate_1              | 20200605111551   messages                       Applied   
kratos-migrate_1              | 20200605111551   messages                       Applied   
kratos-migrate_1              | 20200605111551   messages                       Applied   
kratos-migrate_1              | 20200607165100   settings                       Applied   
kratos-migrate_1              | 20200607165100   settings                       Applied   
kratos-migrate_1              | 20200607165100   settings                       Applied   
kratos-migrate_1              | 20200607165100   settings                       Applied   
kratos-migrate_1              | 20200705105359   rename_identities_schema       Applied   
kratos-migrate_1              | 20200705105359   rename_identities_schema       Applied   
kratos-migrate_1              | 20200705105359   rename_identities_schema       Applied   
kratos-migrate_1              | 20200705105359   rename_identities_schema       Applied   
kratos-selfservice-ui-node_1  | 
kratos-selfservice-ui-node_1  | > kratos-selfservice-ui-node@0.0.1 serve /usr/src/app
kratos-selfservice-ui-node_1  | > node lib/index.js
kratos-selfservice-ui-node_1  | 
kratos-migrate_1              | [POP] 2020/07/16 06:16:06 info - Migrations already up to date, nothing to apply
kratos-migrate_1              | [POP] 2020/07/16 06:16:06 info - 0.0031 seconds
kratos-migrate_1              | Successfully applied SQL migrations!
mailslurper_1                 | time="2020-07-16T06:16:06Z" level=info msg="Starting MailSlurper Server v1.14.1" who=MailSlurper
mailslurper_1                 | time="2020-07-16T06:16:06Z" level=info msg="Connecting to database" who=MailSlurper
mailslurper_1                 | time="2020-07-16T06:16:06Z" level=info msg="Creating database tables..." who=MailSlurper
mailslurper_1                 | time="2020-07-16T06:16:06Z" level=info msg="Created tables successfully." who=MailSlurper
kratos_kratos-migrate_1 exited with code 0
mailslurper_1                 | time="2020-07-16T06:16:06Z" level=info msg="Worker pool configured for 1000 workers" who="SMTP Server Pool"
mailslurper_1                 | time="2020-07-16T06:16:06Z" level=info msg="SMTP listener running on SSL 0.0.0.0:1025" who="SMTP Listener"
mailslurper_1                 | time="2020-07-16T06:16:06Z" level=info msg="1 receiver(s) listening" who="SMTP Listener"
mailslurper_1                 | time="2020-07-16T06:16:06Z" level=info msg="HTTP admin listener running on 0.0.0.0:4436" who=MailSlurper
mailslurper_1                 | ⇨ http server started on [::]:4437
mailslurper_1                 | ⇨ http server started on [::]:4436
kratos_1                      | time=2020-07-16T06:16:06Z level=info msg=Config file loaded successfully. audience=application path=/etc/config/kratos/.kratos.yml service_name=kratos service_version=
kratos_1                      | time=2020-07-16T06:16:06Z level=warning msg=
kratos_1                      | 
kratos_1                      | YOU ARE RUNNING ORY KRATOS IN DEV MODE.
kratos_1                      | SECURITY IS DISABLED.
kratos_1                      | DON'T DO THIS IN PRODUCTION!
kratos_1                      | 
kratos_1                      |  audience=application service_name=kratos service_version=
kratos_1                      | [POP] 2020/07/16 06:16:06 warn - ignoring file .gitignore because it does not match the migration file pattern
kratos_1                      | time=2020-07-16T06:16:06Z level=info msg=Courier worker started. audience=application service_name=kratos service_version=
kratos_1                      | time=2020-07-16T06:16:06Z level=info msg=Software quality assurance features are enabled. Learn more at: https://www.ory.sh/docs/ecosystem/sqa audience=application service_name=kratos service_version=
kratos_1                      | time=2020-07-16T06:16:06Z level=info msg=Starting the admin httpd on: 0.0.0.0:4434 audience=application service_name=kratos service_version=
kratos_1                      | time=2020-07-16T06:16:06Z level=info msg=Starting the public httpd on: 0.0.0.0:4433 audience=application service_name=kratos service_version=
kratos-selfservice-ui-node_1  | Listening on http://0.0.0.0:4455
kratos-selfservice-ui-node_1  | Security mode: cookie
```

and the logs when trying to access the secured dashboard

```
...
kratos-selfservice-ui-node_1  | Listening on http://0.0.0.0:4455
kratos-selfservice-ui-node_1  | Security mode: cookie
kratos-selfservice-ui-node_1  | GET /dashboard 302 66 - 1043.205 ms
kratos-selfservice-ui-node_1  | No request found in URL, initializing auth flow.
kratos-selfservice-ui-node_1  | GET /auth/login 302 148 - 3.019 ms
kratos-selfservice-ui-node_1  | Error: connect EHOSTUNREACH 172.20.0.5:4433
kratos-selfservice-ui-node_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
kratos-selfservice-ui-node_1  | GET /.ory/kratos/public/self-service/browser/flows/login 500 11460 - 1155.391 ms
kratos-selfservice-ui-node_1  | GET /index.css 304 - - 2.618 ms
kratos-selfservice-ui-node_1  | GET /typography.css 304 - - 3.238 ms
kratos-selfservice-ui-node_1  | GET /form.css 304 - - 4.388 ms
kratos-selfservice-ui-node_1  | GET /auth.css 304 - - 0.833 ms
kratos-selfservice-ui-node_1  | GET /favicon.ico 302 22 - 1.085 ms

```

**Comment by aeneasr** [comment] 2020-07-16 07:38
Ok, that looks all good. The only other thing which could happen would be that the Docker-internal DNS resolution isn't properly working or that the internal network is somehow broken. Can you access `http://localhost:4433/health/alive` from your browser or is that also broken?

**Comment by aeneasr** [comment] 2020-07-16 07:39
Oh and could you do a quick `git status` and `git rev-parse HEAD` for me?

**Comment by cdreier** [comment] 2020-07-16 09:00
`http://localhost:4433/health/alive` is working ->

```
{"status":"ok"}
```

i am on the `v0.4.6-alpha.1` tag, changed nothing

```
(tag:v0.4.6-alpha.1 ✓) kratos git status
HEAD losgelöst bei v0.4.6-alpha.1
nichts zu committen, Arbeitsverzeichnis unverändert

(tag:v0.4.6-alpha.1 ✓) kratos git rev-parse HEAD
ad90e772cf59a33b213bc0fb782959a1685d9741
```

**Comment by aeneasr** [comment] 2020-07-16 09:25
Ok, that's very strange and really speaks for a network issue within docker. Without direct access to your system (which would probably also not work due to time constraints :D) I don't think I'll be able to help out here except for pointing you to [this article](https://success.docker.com/article/troubleshooting-container-networking).

**Comment by aeneasr** [comment] 2020-07-23 15:25
Closing because unable to reproduce

**Closed by aeneasr** 2020-07-23 15:25 UTC
