### ISSUE TITLE
Postgres: courier_messages body too small

### ISSUE THREAD

**Issue by torepettersen** [ory/kratos#359] opened 2020-04-23 08:05 UTC
**Describe the bug**

When using Postgres (probably also similar for MySQL) registration with password strategy runs into an error "{"error":{"code":500,"message":"pq: value too long for type character varying(255)"}}".

Manually changing the type for courier_messages body to "TEXT" resolves the problem, so my assumption is that this field need to be longer.

Having a look at fizz it seems like this would be a problem for Postgres and MySQL since strings there defaults to varchar with a length of 255. But it does not seem like a problem for SQLite which defaults to TEXT.

**Comment by aeneasr** [comment] 2020-04-23 08:14
Thank you! This is [fixed on master](https://github.com/ory/kratos/blob/master/persistence/sql/migrations/20191100000011_courier_body_type.up.fizz) and a dupe of #269

**Closed by aeneasr** 2020-04-23 08:14 UTC
