### ISSUE TITLE
Self service endpoints require header Accept: application/json but not documented.

### ISSUE THREAD

**Issue by cairin** [ory/kratos#2291] opened 2022-03-05 10:04 UTC
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

As seen in the [httpclient docs](https://github.com/ory/kratos/blob/master/internal/httpclient/docs/V0alpha2Api.md), most endpoints require the header `Accept: application/json`, but this is not documented anywhere else.

This seems to work fine when `POST` endpoints are called, but `GET` endpoints fail.

`application/json` is not a [default Accept header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation/List_of_default_Accept_values) so it should probably be documented that in some circumstances this is required.

This is not an issue when using the kratos-client, however if you try call these endpoints with fetch they don't work without manually setting the header.

### Reproducing the bug

1. Have kratos running
2. Call out to kratos using fetch:

```js
// Throws 'ECONNREFUSED':
fetch('http://domain/self-service/login/browser')

// Works fine
fetch('http://domain/self-service/login/browser', { headers: {Accept: 'application/json'}})
```

### Relevant log output

```shell
Get FetchError: {
  message: "request to http://ui_url/login?flow=24016091-9759-4463-9964-b5b9df4cc06b failed, 
reason: connect ECONNREFUSED 127.0.0.1:80",
  type: "system",
  errno: "ECONNREFUSED",
  code: "ECONNREFUSED",
}

ui_url is replaced with kratos config value.
```

### Version

0.21.5

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm

### Additional Context

We are using [remix.run](https://remix.run/) which polyfills the [web fetch api](https://remix.run/docs/en/v1/other-api/fetch#globally-available) globally so it can be used in their server side functions.

Thus we ran into this issue when implementing some of the enpoints using fetch.

**Comment by aeneasr** [comment] 2022-03-05 10:56
Thank you for the report and great to see remix.run used with Ory :)

Could you clarify where you would expect this? Ory Kratos is capable of both "browser" requests and AJAX (fetch) requests. Depending on the client type (are you opening a HTML page in the browser?) it repsonds differently.

The error you see with ERRCONREFUSED is coming, because the redirect ends up at `http://ui_url`, which is apparently a fake URL. This is the case when browser interface directly with Kratos (and not with AJAX).

This is documented in several places (see examples below), so it would be helpful to understand where exactly you'd expect this to be written!

* https://www.ory.sh/docs/kratos/self-service/flows/user-registration#registration-for-client-side-ajax-browser-clients
* https://www.ory.sh/docs/kratos/self-service/flows/user-registration#registration-for-api-clients-and-clients-without-browsers
* https://www.ory.sh/docs/kratos/reference/api#operation/submitSelfServiceRecoveryFlow
* https://www.ory.sh/docs/kratos/concepts/browser-redirect-flow-completion

**Comment by cairin** [comment] 2022-03-05 17:18
Okay I see what is happening.

We are sending an AJAX request (using fetch) from the remix loader function, which happens server side. In fact all our interactions happen server side, but are submitted using the [web fetch api](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) that [remix makes available](https://remix.run/docs/en/v1/other-api/fetch#globally-available) to execute server side.

And because we're running both kratos and our frontend in the same cluster, the redirect doesn't resolve because it doesn't know about the DNS at the pod level. So the automatic redirect can't possibly resolve. However by specifying the Accept header the response doesn't include a redirect as [mentioned here](https://www.ory.sh/docs/kratos/reference/api#:~:text=If%20this%20endpoint%20is%20called%20with%20a%20Accept%3A%20application/json%20HTTP%20header%2C%20the%20response%20contains%20the%20flow%20without%20a%20redirect.%20In%20the%20case%20of%20an%20error%2C%20the%20error.id%20of%20the%20JSON%20response%20body%20can%20be%20one%20of%3A).

I see your examples do actually specify that the Accept must be set. I was looking at the [api reference](https://www.ory.sh/docs/kratos/reference/api) which only mentions setting the Accept header for the `POST` requests! But we would need it for all the requests.

**Comment by aeneasr** [comment] 2022-03-07 12:05
Could you clarify which methods in the API docs are missing the correct accept header? We can fix it very quickly then :)

**Comment by aeneasr** [comment] 2022-04-11 20:16
I'm not sure if we can make that parameter part of the headers, at least for OpenAPI. We have a `Produces: application/json` annotation which tells the SDKs and OpenAPI Generator to set `Accept: application/json`. So from that perspective, it should be fine as soon as you use the generated SDKs or the OpenAPI spec automatically. If that's not the case, the problem is probably a broken generator which would need to be reported over at: https://github.com/OpenAPITools/openapi-generator

**Comment by cairin** [comment] 2022-04-20 14:27
Ahh the docs are generated from the OpenAPI spec? If that's the case then you can close this.

We don't use the generated SDK because it uses axios, and it was simpler to use the endpoints directly rather than configure a generator to use fetch.

**Comment by aeneasr** [comment] 2022-04-20 17:25
Ok, closing this then :)

**Closed** 2022-04-20 17:26 UTC
Labels: bug
