### ISSUE TITLE
Customizable/translatable error messages

### ISSUE THREAD

**Issue by torepettersen** [ory/kratos#363] opened 2020-04-26 07:13 UTC
**Is your feature request related to a problem? Please describe.**

Some of the default error messages in the registration/login are a bit long and doesn't fit very well into my website. Also, error messages need to be translatable, to support multiple languages.

**Describe the solution you'd like**

When JSON support https://github.com/ory/kratos/issues/44 is implemented an error code could be delivered with the JSON response for each error. This error code could easily be used to customize/translate the error messages on the client-side.

**Describe alternatives you've considered**

Add configuration that allows for customizing/translation of error messages.

**Comment by aeneasr** [comment] 2020-04-26 09:29
Thank you for opening this issue! I believe this is a dupe of #185 ?

**Comment by torepettersen** [comment] 2020-04-26 20:42
I guess you are right. Feel free to close if you don't see any additional value in keeping this open.

**Comment by aeneasr** [comment] 2020-04-27 07:37
Ok, will be closing to keep the repo tidy :)

**Closed by aeneasr** 2020-04-27 07:37 UTC
