### ISSUE TITLE
Investigate potentially empty response from server

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#429] opened 2020-05-19 13:11 UTC
https://community.ory.sh/t/ory-kratos-empty-responses-from-server-in-verification-flow/1746/3

**Comment by avamonitoring** [comment] 2020-05-27 19:40
Duplicate of #436.

**Comment by aeneasr** [comment] 2020-05-27 20:20
Ah perfect - so those two are related!

**Closed** 2020-05-28 07:30 UTC
Labels: investigate
