### ISSUE TITLE
OIDC registration method ignores Claims.EmailVerified

### ISSUE THREAD

**Issue by marcinkoziej** [ory/kratos#1057] opened 2021-02-09 12:07 UTC
Kratos v0.5.4-alpha.1 on Ubuntu Linux.

I have properly configured OIDC method with Google, but I think this issue affects any provider that returns email_verified: true in claims.

On identity creation, Kratos will simply ignore this claim, and create VerifiableAddresses as unverified, and will send a verification link.

I tried to investigate it a bit:

Registration flow for Generic OIDC method

1. The OIDC configuration works well in that it receives Claims properly from Google:
The broken down Printf() of `Claims` struct looks like this:
```
mapper_jsonnet_url=file:///ory/kratos/google.jsonnet oidc_claims=&{https://accounts.google.com 
10625425596338xxxxxx600 
Marcin Ossowski Marcin Ossowski      
https://lh3.googleusercontent.com/a-/AOh14GXXXXXXXXXXXXXXv1f9RmaVNHpmwgv=s96-c  
marcin@example.com <-- my email here
 true        <- email_verified here
 en  
false 
0} oidc_provider=google service_name=kratos service_version=
``` 
2. Kratos is absolutely not using this information :O 
   - In `processRegistration`, the identity is created (traits are generated by jsonnet mapper and yield a good result with first_name, last_name, email)
   - The PostRegistrationPrePersistHooks are run - and there are 0 such hooks
   - The PostRegistrationPostPersisHoox are run - there is just one, which actually sends me the verifiaction email
3. Ideally, there would be a PostRegistrationPrePersistHooks called "recognize_verification" or similar that would mark `identity.VerifiableAddresses` corresponding to identity.email as verified; Or, the code which creates VerifiableAdresses array with elements, would create such address already verified (I was not able to localize the code that does it though; it's possible that it has access only to `traits` but not to `Claims`, in which case it will not be able to access the `Claims.EmailVerified`.

The hook code is very convoluted to me with many levels of abstraction, so I must admin I have no idea how to properly fix this - I should probably create an issue based on this discussion topic, right ?

_Originally posted by @marcinkoziej in https://github.com/ory/kratos/discussions/1045#discussioncomment-352747_

**Comment by aeneasr** [comment] 2021-02-09 13:55
Thank you for the report. :) Can you please share your jsonnet code?

**Comment by marcinkoziej** [comment] 2021-02-09 15:31
kratos.yml relevant parts:
```
  methods:
    link:
      enabled: true
    password:
      enabled: true
    oidc:
      enabled: true
      config:
        providers:
          - id: google
            provider: google # same result with generic, google provider defaults to generic implementation
            client_id: "XXXXX"
            client_secret: "YYYY"
            issuer_url: https://accounts.google.com
            auth_url: https://accounts.google.com/o/oauth2/v2/auth
            token_url: https://oauth2.googleapis.com/token
            mapper_url: file:///ory/kratos/google.jsonnet
            scope:
              - email
              - profile
            requested_claims: 
              id_token:
                email:
                  essential: true
                email_verified:
                  essential: true
                given_name:
                  essential: true
                family_name: null

```

google.jsonnet (just adapted one from the doc):
```
local claims = {
  email_verified: true
} + std.extVar('claims');

{
  identity: {
    traits: {
      [if "email" in claims && claims.email_verified then "email" else null]: claims.email,
			first_name: claims.given_name,
			last_name: claims.family_name,
    },
  },
}

```

user.json:
```
{
  "$id": "https://fixthestatusquo.com/schemas/identity.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Person",
  "type": "object",
  "properties": {
    "traits": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "format": "email",
          "title": "E-Mail",
          "minLength": 3,
          "ory.sh/kratos": {
            "credentials": {
              "password": {
                "identifier": true
              }
            },
            "verification": {
              "via": "email"
            },
            "recovery": {
              "via": "email"
            }
          }
        },
        "first_name": {
          "type": "string",
          "title": "First name",
          "minLength": 1
        },
        "last_name": {
          "type": "string",
          "title": "Last name",
          "minLength": 1
        }
      },
      "required": [
        "first_name",
        "last_name",
        "email"
      ],
      "additionalProperties": false
    }
  }
}
```

**Comment by aeneasr** [comment] 2021-02-09 15:33
Right, so the problem is that `claims.email_verified` can't be passed to the identity, correct?

**Comment by marcinkoziej** [comment] 2021-02-09 18:09
I do not know if it can't be passed, or whether it can be passed to internal APIs like hook ones, but the data flow is as follows:

1. Google returns us claims: 
  given_name: 'Marcin', family_name: 'Ossowski', email: 'marcin@example.com', email_verified: true
2. The claims is mapped via JSONNET mapper 
   - which returns map with `traits` object with { first_name: 'Marcin', last_name: 'Ossowski', email: 'marcin@example.com' } keys. We cannot put "email_verified" into traits map because it is not a trait [1]
3. The output from JSONNET map is given to Identity persister. 

Maybe the jsonnet could be added an "extra" section where email_verified could be given (as below), or the identity creator would use the Claims somehow. Not sure if / how complex is the Kratos internal interface change necessary
```
local claims = {
  email_verified: true
} + std.extVar('claims');

{
  identity: {
    traits: {
      [if "email" in claims && claims.email_verified then "email" else null]: claims.email,
			first_name: claims.given_name,
			last_name: claims.family_name,
    },
    extra_info: { email_verified: claims.email_verified }
  },
}


```


[1] I understand that traits are only ones defined in user.json, and if I would add "email_verified" in there, it would appear as input on registration etc.

**Comment by aeneasr** [comment] 2021-02-10 07:24
Thank you for the information, I now remember this - I thought created an issue to track adding this type of meta information (email_verified) to the JsonNet response but apparently I did not.

The idea would be to allow defining some extra things, such as verified, in the JsonNet response. I was thinking of allowing the verified_addresses to the JsonNet which would address your issue. What do you think?

**Comment by marcinkoziej** [comment] 2021-02-12 09:27
If we can use jsonnet array comprehension to map over verified_addresses and update `status` and `verified` the item matching traits.email, that would work.
But it also would expose some Kratos internals to jsonnet code. What if someone returns a verified_address.status that is not allowed for instance? Of course we can just fail with log message, but this approach exposes this implementation detail...

**Comment by aeneasr** [comment] 2021-02-17 15:21
Sorry for my late reply, was deep down in Kubernetes and CRDB migration issues ;)

Hm yeah that is true - if a verified email is added which is not in the traits, the record will be purged on the next identity update as the verifier can't find it in the traits. So there should be some checking going on and if the mail does not exist result in an error imo.

**Comment by borchero** [comment] 2021-03-14 20:33
While this might not a fully satisfactory solution, I'm now going with the following (stripped) user configuration to solve this problem:

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://id.taskfleet.io/-/schema/user.json",
  "title": "User",
  "description": "The schema for any user.",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "traits": {
      "type": "object",
      "oneOf": [
        { "required": ["primaryEmail"] },
        { "required": ["secondaryEmails"] },
        { "required": ["primaryEmail", "secondaryEmails" ]}
      ],
      "additionalProperties": false,
      "properties": {
        "primaryEmail": {
          "type": "string",
          "format": "email",
          "ory.sh/kratos": {
            "credentials": {
              "password": {
                "identifier": true
              }
            },
            "recovery": {
              "via": "email"
            },
            "verification": {
              "via": "email"
            }
          }
        },
        "secondaryEmails": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "format": "email"
          }
        }
      }
    }
  }
}
```

Accordingly, I use the following Jsonnet configuration:

```jsonnet
local claims = {
  email_verified: false
} + std.extVar('claims');

{
  identity: {
    traits: {
      [if "email" in claims && claims.email_verified then "secondaryEmails" else null]: [
        claims.email
      ],
    },
  }
}
```

When someone signs up with a social login, no email is being sent and the account cannot be recovered using the email. Since it's linked to the OIDC provider anyway, I figured that this should not be a problem.

Anyway, the user may still add a primary email address for which he/she uses a password.

**Caveat:** Of course, your identity provider might now be "abused" by allowing `secondaryEmails` to be set without providing any `primaryEmail`. Interestingly, ORY Kratos does not create an identity in that case, but returns the following error (which is fine for me):

```json
{
  "id": "<id>",
  "errors": [
    {
      "code": 500,
      "reason": "No login identifiers (e.g. email, phone number, username) were set. Contact an administrator, the identity schema is misconfigured.",
      "status": "Internal Server Error",
      "message": "An internal server error occurred, please contact the system administrator"
    }
  ]
}
```

**Comment by aeneasr** [comment] 2021-03-15 09:06
Great, thank you for the workaround! What do you think about the proposals above?

**Comment by borchero** [comment] 2021-03-15 10:53
To be honest, I don't know if it's even necessary to change anything in Kratos. Adding the "verification via email" block basically implies that you want the user to validate that email. If not, I think it is fine to just put it into another trait field.

You can also add the "credentials ... password ... identifier" block to the email retrieved from an OAuth provider so you don't end up with duplicate emails in the system.

**Comment by marcinkoziej** [comment] 2021-04-08 12:06
@borchero @aeneasr  My use case is to check in the app whether the email is verified (by the verification link if this is plain email sign in, or google-verified if it is oidc sign in). In case email is not verified, i do not let the user in at all, until it is verified.
I'm not sure the workaround you have proposed addresses such workflow.

**Comment by johanforssell** [comment] 2021-05-05 12:17
I would also like to be rid of the "please verify your email" when using a specific OIDC provider, it's sometimes superflous.

**Comment by aeneasr** [comment] 2021-05-08 11:02
@johanforssell I think there are many good ideas in this thread. If you have other ideas how to address the issue or want to make a contribution we would be super happy to get your feedback. +1 issues however help noone and are against our contribution guidelines so please refrain from that. Thank you for your understanding! :)

**Comment by vstreame** [comment] 2022-11-02 23:53
We just hit this one as well. It would make our life (and the lives of our users) much better if we don't need to re-verify an email the OIDC provider has already marked as verified. Only if they _change_ the email from what the OIDC provider provides us should we re-triggering the verify flow.

**Comment by Rodeoclash** [comment] 2022-11-22 05:14
Agreed with this one as well, although I'd say that you need some level of control over this. Some OIDC providers I might trust more than others when it comes to verified email addresses.

**Comment by Sytten** [comment] 2023-05-13 01:37
Have we made any progress on that one? @aeneasr 
Happy to contribute to the code if we have a consensus on what we want to do. 
For me either jsonnet (https://github.com/ory/kratos/issues/1057#issuecomment-776133807) or a setting on the kratos.yml would do:
```yml
- id: google
  verified:
    claim: email_verified
```

**Closed** 2023-08-22 14:30 UTC
