### ISSUE TITLE
Kratos on kubernetes is not ready with readiness probe

### ISSUE THREAD

**Issue by viters** [ory/kratos#1851] opened 2021-10-18 08:24 UTC
I think I may have the same problem. I am deploying Kratos using Kubernetes (minikube), and I have this strange situation:

Whenever I add
```yaml
readinessProbe:
  httpGet:
    path: /health/ready
    port: http-admin
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 5
```
to deployment specification, the deployment will not start ever - pod returns 503 (with no further explanation) no matter how much time passes. 
```
time=2021-10-12T20:30:34Z level=info msg=started handling request http_request=map[headers:map[accept:*/* connection:close user-agent:kube-probe/1.22] host:172.17.0.4:4434 method:GET path:/health/alive query:<nil> remote:172.17.0.1:57652 scheme:http]
time=2021-10-12T20:30:34Z level=info msg=started handling request http_request=map[headers:map[accept:*/* connection:close user-agent:kube-probe/1.22] host:172.17.0.4:4434 method:GET path:/health/ready query:<nil> remote:172.17.0.1:57650 scheme:http]
time=2021-10-12T20:30:34Z level=info msg=completed handling request http_request=map[headers:map[accept:*/* connection:close user-agent:kube-probe/1.22] host:172.17.0.4:4434 method:GET path:/health/alive query:<nil> remote:172.17.0.1:57652 scheme:http] http_response=map[headers:map[content-type:application/json; charset=utf-8] size:16 status:200 text_status:OK took:646.625µs]
time=2021-10-12T20:30:35Z level=info msg=completed handling request http_request=map[headers:map[accept:*/* connection:close user-agent:kube-probe/1.22] host:172.17.0.4:4434 method:GET path:/health/ready query:<nil> remote:172.17.0.1:57650 scheme:http] http_response=map[headers:map[content-type:application/json; charset=utf-8] size:69 status:503 text_status:Service Unavailable took:1.076644834s]
```

If I do not add `readinessProbe`, the Kratos will start right away and I am able to call `/health/ready` from outside - and it returns 200.

_Originally posted by @viters in https://github.com/ory/kratos/issues/1749#issuecomment-941495349_

**Comment by aeneasr** [comment] 2021-10-19 07:00
Thank you for contributing to this repository by creating an issue!

Unfortunately, your issue lacks vital information, such as log files, the error message, the software version, your configuration or other pieces of the puzzle.

Please also ensure that your issue is appropriately formatted. If you do not know how to write markdown, you can find help [here](https://guides.github.com/features/mastering-markdown/).

Helping you with your problem is only possible if you share this information, and it will save a lot of time of back and forth on your as well as our end!

For this reason, this repository uses [issue templates](../tree/master/.github/ISSUE_TEMPLATE) which you can select when pressing "New issue". Please use one of those issue templates to fill in the required information. You can either create a new issue for this purpose and close this one, or leave a comment.

If you have used an issue template and see this comment, it means that your description lacks information that allows maintainers to understand what problem you are facing and how to reproduce it.

> Do not edit the original post as we will not be notified when you do so.

If you do not provide the requested information, this issue will be closed. Thank you for your understanding!

**Comment by avamonitoring** [comment] 2021-11-06 09:27
This is what works for us on k8s 1.21.5 (and previous versions). It's basically the default settings:

```
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /health/ready
        port: http-admin
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
```

**Comment by aeneasr** [comment] 2021-11-06 10:49
Closing this because details are lacking - please to open another one if you have a reproducible case :)

**Closed by aeneasr** 2021-11-06 10:49 UTC
