### ISSUE TITLE
Ability to get identities by other field than id (e.g.: get identity associated with an email address)

### ISSUE THREAD

**Issue by cortopy** [ory/kratos#1467] opened 2021-06-28 16:47 UTC
**Is your feature request related to a problem? Please describe.**

Right now the only way to get information about a user is to have the identity's id beforehand. However, client applications may not be aware of identity ids until a user is logged in.

Being able to search for identities would allow things like:

- Knowing if an email address is already registered with kratos
- A backend microservice can get user traits just by knowing the email address

The good thing about this is that backend clients would be able to get user data without intervention from user

**Describe the solution you'd like**

Being able to query something like `GET /identities/email/{email}` using an admin endpoint. 

It could return the identity (without token) associated with that email if it exists

**Describe alternatives you've considered**

1. `GET /identities` and paginate/scan data until a match is found but this would be extremely slow
2. Save in my own database a table with pointers between kratos ids and email addresses. But going this route is making kratos less useful as a full IAM

**Comment by aeneasr** [comment] 2021-06-29 10:09
Potentially solved by https://github.com/ory/kratos/pull/1420

**Comment by aeneasr** [comment] 2021-07-05 11:16
Yup, dupe of #1420

**Closed by aeneasr** 2021-07-05 11:16 UTC
