### ISSUE TITLE
Migration path for existing user/account tables

### ISSUE THREAD

**Issue by Jasrags** [ory/kratos#500] opened 2020-06-09 16:01 UTC
Hello, I was speaking with Vincent on slack and he suggested that I post an enhancement issue.

I'm looking for a way to use kratos as our identity management system, we currently run a legacy PHP system with a users table with millions of existing users. I would love to have a migration path from legacy into kratos with hopefully the least amount of user friction (Forced log-out/password changes). We are totally fine moving auth specific info into a new table, but anything that can be done to ease this change would be perfect.

**Describe alternatives you've considered**

At this point it's just kratos or we roll our own.

**Comment by aeneasr** [comment] 2020-06-10 08:00
So there is currently no option to do this, it's basically blocked by #200 (see also #435 and #325). It **will** however be possible to import users even if you currently use something like BCrypt or some other password hashing algorithm.

It won't be possible to do a switch without a logout however, because Kratos can't work with your current session system. You could however solve that on a proxy/application level and use two session stores (Kratos and your current system) for the migration period, validating the session against both systems.

However, this feature will take a bit more time as we're currently solving other issues. But you can take me by my word that this will be possible and that I will also personally work on this feature most likely in Q3 2020.

**Comment by aeneasr** [comment] 2020-07-27 12:48
I'm closing this as a dupe of #605 which contains much more detail.

@Jasrags what hashing algorithm do you currently use?

**Closed by aeneasr** 2020-07-27 12:48 UTC

**Comment by Jasrags** [comment] 2020-07-27 15:58
@aeneasr bcrypt, and thank you
