### ISSUE TITLE
Wrong status code in registration

### ISSUE THREAD

**Issue by torepettersen** [ory/kratos#365] opened 2020-04-26 07:34 UTC
**Describe the bug**

When I am trying to register a user with a password strategy and get a validation error, the status code that is being given back is 500 which indicates a server error, although this could be fixed by the user.

Example response:
{"error":{"code":500,"message":"I[#/password] S[] the password does not fulfill the password policy because: the password has been found in at least 121251 data breaches and must no longer be used."}}}

**Expected behavior**

User errors should send back a status code in the 400 range.
I would suggest 422 for validation errors and 409 for duplicate email/username.

**Comment by aeneasr** [comment] 2020-04-26 09:29
Thank you for opening this issue! I believe this is a dupe of #185 ?

**Comment by torepettersen** [comment] 2020-04-26 20:42
I guess you are right. Feel free to close if you don't see any additional value in keeping this open.

**Comment by aeneasr** [comment] 2020-04-27 07:38
Ok, will be closing to keep the repo tidy :)

**Closed by aeneasr** 2020-04-27 07:38 UTC
