### ISSUE TITLE
Calling PUT to update an identity sometimes return 409 

### ISSUE THREAD

**Issue by sisca-goodnotes** [ory/kratos#2994] opened 2022-12-30 05:12 UTC
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Hi folks, I’m experiencing an issue when using update an identity endpoint on Kratos.
When our service calls to update an identity (PUT), kratos sometimes returns 409 with the following message:
```
"error":{"code":409,"status":"Conflict","message":"Unable to insert or update resource because a resource with that value exists already"}
```

Upon further investigation on the postgres db, this is the error log:
```
2022-12-16 18:13:18 UTC:10.0.156.122(41284):postgres@postgres:[3459]:ERROR:  duplicate key value violates unique constraint "identity_credentials_pkey"
2022-12-16 18:13:18 UTC:10.0.156.122(41284):postgres@postgres:[3459]:DETAIL:  Key (id)=(68ad922a-026d-40ac-8029-21a4b89c4062) already exists.
2022-12-16 18:13:18 UTC:10.0.156.122(41284):postgres@postgres:[3459]:STATEMENT:  INSERT INTO "identity_credentials" ("config", "created_at", "id", "identity_credential_type_id", "identity_id", "nid", "updated_at", "version") VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2022-12-16 18:13:18 UTC:10.0.156.122(41284):postgres@postgres:[3459]:ERROR:  current transaction is aborted, commands ignored until end of transaction block
```

I am confused as to why the log shows INSERT query, where from my understanding and update endpoint should do UPDATE query. Any idea what might be the issue?
Also, what is the primary key (id)=(68ad922a-026d-40ac-8029-21a4b89c4062) used in the DB? I assumed it would be kratos-id, but it is different from the kratos-id of the update request and when I try to get the identity using that id it returns 404.

### Reproducing the bug

1. Do `kubectl port-forward`
2. Run several update queries on the same identity concurrently

For example, run this script in 2 different terminals:
```
for i in $(eval echo {1..100})

do
curl --location --request PUT 'http://localhost:4434/admin/identities/<kratos_id>' \
--header 'Content-Type: application/json' \
--data-raw '{
       "traits": {
           ...
        }
}'
done
```

### Version

v0.10.0

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

Kubernetes with Helm

### Additional Context

I also raised this issue in slack https://ory-community.slack.com/archives/C02PSRUGUAV/p1671425653009099

**Comment by aeneasr** [comment] 2023-10-05 12:32
Closing due to age - the issue is that the record already exists in the DB

**Closed by aeneasr** 2023-10-05 12:32 UTC
Labels: bug
