### ISSUE TITLE
MariaDB 10.4.7 database migrate error: Field 'created_at' doesn't have a default value

### ISSUE THREAD

**Issue by zhshize** [ory/kratos#770] opened 2020-10-16 08:39 UTC
I ran kratos migration with mariadb connection and I got an error.

1. Run migrate:
`./kratos migrate sql "mysql://kratos:********@tcp(localhost:3306)/kratos?multiStatements=true"`
2. Got an error
```
WARN[2020-10-16T16:12:53+08:00] No config file was defined and no file was found in $HOME/.kratos.yaml  audience=application error=map[message:Config File ".kratos" Not Found in "[/home/********]"] service_name=kratos service_version=
The following migration is planned:

Version          Name                                      Status    
20191100000001   identities                                Pending   
20191100000001   identities                                Pending   
20191100000001   identities                                Pending   
20191100000001   identities                                Pending   
20191100000002   requests                                  Pending   
20191100000002   requests                                  Pending   
20191100000002   requests                                  Pending   
20191100000002   requests                                  Pending   
20191100000003   sessions                                  Pending   
20191100000003   sessions                                  Pending   
20191100000003   sessions                                  Pending   
20191100000003   sessions                                  Pending   
20191100000004   errors                                    Pending   
20191100000004   errors                                    Pending   
20191100000004   errors                                    Pending   
20191100000004   errors                                    Pending   
20191100000005   identities                                Pending   
20191100000006   courier                                   Pending   
20191100000006   courier                                   Pending   
20191100000006   courier                                   Pending   
20191100000006   courier                                   Pending   
20191100000007   errors                                    Pending   
20191100000007   errors                                    Pending   
20191100000007   errors                                    Pending   
20191100000007   errors                                    Pending   
20191100000008   selfservice_verification                  Pending   
20191100000008   selfservice_verification                  Pending   
20191100000008   selfservice_verification                  Pending   
20191100000008   selfservice_verification                  Pending   
20191100000009   verification                              Pending   
20191100000010   errors                                    Pending   
20191100000010   errors                                    Pending   
20191100000010   errors                                    Pending   
20191100000010   errors                                    Pending   
20191100000011   courier_body_type                         Pending   
20191100000011   courier_body_type                         Pending   
20191100000011   courier_body_type                         Pending   
20191100000011   courier_body_type                         Pending   
20191100000012   login_request_forced                      Pending   
20191100000012   login_request_forced                      Pending   
20191100000012   login_request_forced                      Pending   
20191100000012   login_request_forced                      Pending   
20200317160354   create_profile_request_forms              Pending   
20200317160354   create_profile_request_forms              Pending   
20200317160354   create_profile_request_forms              Pending   
20200317160354   create_profile_request_forms              Pending   
20200401183443   continuity_containers                     Pending   
20200401183443   continuity_containers                     Pending   
20200401183443   continuity_containers                     Pending   
20200401183443   continuity_containers                     Pending   
20200402142539   rename_profile_flows                      Pending   
20200402142539   rename_profile_flows                      Pending   
20200402142539   rename_profile_flows                      Pending   
20200402142539   rename_profile_flows                      Pending   
20200519101057   create_recovery_addresses                 Pending   
20200519101057   create_recovery_addresses                 Pending   
20200519101057   create_recovery_addresses                 Pending   
20200519101057   create_recovery_addresses                 Pending   
20200519101058   create_recovery_addresses                 Pending   
20200601101000   create_messages                           Pending   
20200601101000   create_messages                           Pending   
20200601101000   create_messages                           Pending   
20200601101000   create_messages                           Pending   
20200601101001   verification                              Pending   
20200605111551   messages                                  Pending   
20200605111551   messages                                  Pending   
20200605111551   messages                                  Pending   
20200605111551   messages                                  Pending   
20200607165100   settings                                  Pending   
20200607165100   settings                                  Pending   
20200607165100   settings                                  Pending   
20200607165100   settings                                  Pending   
20200705105359   rename_identities_schema                  Pending   
20200705105359   rename_identities_schema                  Pending   
20200705105359   rename_identities_schema                  Pending   
20200705105359   rename_identities_schema                  Pending   
20200810141652   flow_type                                 Pending   
20200810141652   flow_type                                 Pending   
20200810141652   flow_type                                 Pending   
20200810141652   flow_type                                 Pending   
20200810161022   flow_rename                               Pending   
20200810161022   flow_rename                               Pending   
20200810161022   flow_rename                               Pending   
20200810161022   flow_rename                               Pending   
20200810162450   flow_fields_rename                        Pending   
20200810162450   flow_fields_rename                        Pending   
20200810162450   flow_fields_rename                        Pending   
20200810162450   flow_fields_rename                        Pending   
20200812124254   add_session_token                         Pending   
20200812124254   add_session_token                         Pending   
20200812124254   add_session_token                         Pending   
20200812124254   add_session_token                         Pending   
20200812160551   add_session_revoke                        Pending   
20200812160551   add_session_revoke                        Pending   
20200812160551   add_session_revoke                        Pending   
20200812160551   add_session_revoke                        Pending   
20200830121710   update_recovery_token                     Pending   
20200830121710   update_recovery_token                     Pending   
20200830121710   update_recovery_token                     Pending   
20200830121710   update_recovery_token                     Pending   
20200830130642   add_verification_methods                  Pending   
20200830130642   add_verification_methods                  Pending   
20200830130642   add_verification_methods                  Pending   
20200830130642   add_verification_methods                  Pending   
20200830130643   add_verification_methods                  Pending   
20200830130643   add_verification_methods                  Pending   
20200830130643   add_verification_methods                  Pending   
20200830130643   add_verification_methods                  Pending   
20200830130644   add_verification_methods                  Pending   
20200830130644   add_verification_methods                  Pending   
20200830130644   add_verification_methods                  Pending   
20200830130644   add_verification_methods                  Pending   
20200830130645   add_verification_methods                  Pending   
20200830130645   add_verification_methods                  Pending   
20200830130645   add_verification_methods                  Pending   
20200830130645   add_verification_methods                  Pending   
20200830130646   add_verification_methods                  Pending   
20200830130646   add_verification_methods                  Pending   
20200830130646   add_verification_methods                  Pending   
20200830130646   add_verification_methods                  Pending   
20200830154602   add_verification_token                    Pending   
20200830154602   add_verification_token                    Pending   
20200830154602   add_verification_token                    Pending   
20200830154602   add_verification_token                    Pending   
20200830172221   recovery_token_expires                    Pending   
20200830172221   recovery_token_expires                    Pending   
20200830172221   recovery_token_expires                    Pending   
20200830172221   recovery_token_expires                    Pending   
20200831110752   identity_verifiable_address_remove_code   Pending   
20200831110752   identity_verifiable_address_remove_code   Pending   
20200831110752   identity_verifiable_address_remove_code   Pending   
20200831110752   identity_verifiable_address_remove_code   Pending   

To skip the next question use flag --yes (at your own risk).
Do you wish to execute this migration plan? [y/n]: y
[POP] 2020/10/16 16:12:54 info - > identities
[POP] 2020/10/16 16:12:54 info - > requests
[POP] 2020/10/16 16:12:54 info - > sessions
[POP] 2020/10/16 16:12:54 info - > errors
[POP] 2020/10/16 16:12:54 info - > identities
[POP] 2020/10/16 16:12:54 info - > courier
[POP] 2020/10/16 16:12:54 info - > errors
[POP] 2020/10/16 16:12:54 info - > selfservice_verification
[POP] 2020/10/16 16:12:54 info - > verification
[POP] 2020/10/16 16:12:54 info - > errors
[POP] 2020/10/16 16:12:54 info - > courier_body_type
[POP] 2020/10/16 16:12:54 info - > login_request_forced
[POP] 2020/10/16 16:12:54 info - 0.4487 seconds
An error occurred while connecting to SQL: error executing github.com/ory/kratos:/persistence/sql/migrations/sql/20200317160354_create_profile_request_forms.mysql.up.sql, sql: CREATE TABLE `selfservice_profile_management_request_methods` (
`id` char(36) NOT NULL,
PRIMARY KEY(`id`),
`method` VARCHAR (32) NOT NULL,
`selfservice_profile_management_request_id` char(36) NOT NULL,
`config` JSON NOT NULL,
`created_at` DATETIME NOT NULL,
`updated_at` DATETIME NOT NULL
) ENGINE=InnoDB;
ALTER TABLE `selfservice_profile_management_requests` ADD COLUMN `active_method` VARCHAR (32);
INSERT INTO selfservice_profile_management_request_methods (id, method, selfservice_profile_management_request_id, config) SELECT id, 'traits', id, form FROM selfservice_profile_management_requests;
ALTER TABLE `selfservice_profile_management_requests` DROP COLUMN `form`;: Error 1364: Field 'created_at' doesn't have a default value
```

There is an error "ALTER TABLE \`selfservice_profile_management_requests\` DROP COLUMN \`form\`;: Error 1364: Field 'created_at' doesn't have a default value".

According to [mariadb official document](https://mariadb.com/kb/en/sql-mode/), `STRICT_TRANS_TABLES` SQL mode was added from MariaDB 10.2.4.  This SQL mode disallows inserting null value into a not null column.
So I took this SQL mode away, and migrating works well.

In my opinion, my solution is temporary and not good for production environment.
Is there a solution to migrate with MariaDB 10.2.4+ without taking `STRICT_TRANS_TABLES` SQL mode away?

**Comment by aeneasr** [comment] 2020-10-16 08:49
The problem is that we don't officially support MariaDB and just assume that it's compatible with MySQL queries but apparently that's not the case. We don't have tests or dedicated migration instructions (the underlying DBAL doesn't support MariaDB as well).

While I would love to offer you an easy out here, unfortunately I can't. But what I can do is point you to the projects that would need to have support added for MariaDB - I'm a maintainer there so I can help out a bit. But just as a warning, it will probably be a bit of work!

* https://github.com/gobuffalo/fizz
* https://github.com/gobuffalo/pop

**Comment by aeneasr** [comment] 2020-10-21 08:34
I am closing this because I fear we have to push this upstream (gobuffalo/pop) - sorry!

**Closed by aeneasr** 2020-10-21 08:34 UTC

**Comment by DanielFuchs98** [comment] 2021-01-06 12:10
Adding sql_mode='' to the connection string worked for me.

```
environment:
      - DSN=mysql://user:pass@tcp(ipOfMariadb:3306)/kratos?max_conns=20&max_idle_conns=4&sql_mode=''
```

**Comment by aeneasr** [comment] 2021-01-06 12:14
Oh that's great! Do you have a source where this is described? We can then add it to the docs

**Comment by DanielFuchs98** [comment] 2021-01-06 14:50
Here the doc from mariadb: https://mariadb.com/kb/en/sql-mode/#setting-sql_mode

And here how to set variables on the gorm connection string https://github.com/go-sql-driver/mysql#system-variables

**Comment by aeneasr** [comment] 2021-01-08 08:18
Thank you, I added this to the docs!

**Comment by nkane** [comment] 2024-04-30 03:21
> Adding sql_mode='' to the connection string worked for me.
> 
> ```
> environment:
>       - DSN=mysql://user:pass@tcp(ipOfMariadb:3306)/kratos?max_conns=20&max_idle_conns=4&sql_mode=''
> ```

you're a legend :+1:
