### ISSUE TITLE
Setting up a OIDC secrets via environment variables

### ISSUE THREAD

**Issue by harnash** [ory/kratos#1535] opened 2021-07-13 18:26 UTC
**Describe the bug**

This is the follow up on https://github.com/ory/kratos/discussions/1186. Right now it seems there is no way to properly define Kratos configuration and separate secrets via environment variables. There seems to be mention of env variable `SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS` however I could not make it work properly using the following variable:
* `SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_0_CLIENT_SECRET`

**Reproducing the bug**

1. Create configuration that uses Google as OIDC provider and configure it as described https://www.ory.sh/kratos/docs/guides/sign-in-with-github-google-facebook-linkedin#google ommiting the sensitive fields `client_id` and `client_secrets`
2. Try to specify above secrets using environment variables

_Server logs_

```
The configuration contains values or keys which are invalid:                                                                                                                                      
selfservice.methods.oidc.config.providers.0.client_secret: <nil>                                                                                                                                  
                                                     ^-- one or more required properties are missing
```

**Expected behavior**

To follow best practices it would be really nice to be able to override those variables using environment variables and avoid putting the whole configuration into secret storage.

**Comment by aeneasr** [comment] 2021-07-14 07:33
You could try to JSON encode everything below `SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS` so e.g. `SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS=[{"id":""}]` but not sure if it works tbh 😅

**Comment by harnash** [comment] 2021-07-14 08:07
Nope. It doesn't seem to work.

**Comment by aeneasr** [comment] 2021-07-14 08:09
If you want to investigate, the problem is probably somewhere around here: https://github.com/ory/x/blob/master/configx/koanf_env.go

**Comment by harnash** [comment] 2021-07-14 09:07
Will take a look. But I think it might need some substantial work to make it happen.

**Comment by aeneasr** [comment] 2021-07-14 09:36
Yeah that's quite possible. But it's also possible that it just needs a few lines of code to fix (but quite some time to understand what's going on) :)

**Comment by harnash** [comment] 2021-07-15 11:10
Not a huge success https://github.com/ory/x/pull/374 but some progress.

**Comment by aeneasr** [comment] 2021-07-30 10:14
Have you tried if https://github.com/ory/x/pull/374 works in Ory Kratos as intended? If so, we can bump ory/x here and the close this :)

**Comment by harnash** [comment] 2021-07-30 19:32
Yes it works. However it is far from optimal. It forces anyone to keep the whole `SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS` serialized as a string which is error prone and hard to manage if one have more than one provider setup (might even hit some limits when this string gets to long). I would keep this open and try to find more manageable solution. What do you think?

**Comment by aeneasr** [comment] 2021-08-02 08:01
Ok, sounds good!

**Comment by Mautriz** [comment] 2021-08-10 08:24
Hm, am I missing something ? It keeps giving me `nil` with this env variable set

`SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS=[{"id":"google","provider":"google","client_id":"clientid","client_secret":"secret","mapper_url":"file:///etc/config/kratos/oidc.google.jsonnet","scope":["email","profile"],"requested_claims":{"id_token":{"email":{"essential":true},"email_verified":{"essential":true}}}}]`

**Comment by harnash** [comment] 2021-08-10 11:00
@Mautriz Works just fine in our setup. You are sure this variable is properly escaped? '"' can be tricky in ENV variables/JSON.

**Comment by Mautriz** [comment] 2021-08-10 11:28
I'm not sure what you mean by that, here is the file I use tho [Environment](https://github.com/Mautriz/full-site/blob/main/kratos/.env.example)  

I would highly appreciate if you could help me :P

**Comment by aeneasr** [comment] 2021-08-10 11:50
I don't think this is released yet which is probably the problem here.

**Closed** 2021-12-30 14:42 UTC
