### ISSUE TITLE
Doesn't build on FreeBSD

### ISSUE THREAD

**Issue by hrefhref** [ory/kratos#1645] opened 2021-08-12 14:55 UTC
Kratos (also affects Keto) does not build (`gmake install`) on FreeBSD: 

```
GO111MODULE=on go install -tags sqlite .
# github.com/ory/dockertest/v3/docker/pkg/system
../../go/pkg/mod/github.com/ory/dockertest/v3@v3.6.5/docker/pkg/system/mknod.go:12:19: cannot use dev (type int) as type uint64 in argument to unix.Mknod
gmake: *** [Makefile:63: install] Error 2
```

**Reproducing the bug**

1. Boot a FreeBSD.
2. `pkg install go sqlite3 bash gmake`
3. `ln -s /usr/local/bin/bash /bin/bash` (this is hardcoded in the `Makefile`)
4. Clone Kratos
5. `gmake install`

**Environment**

- Git main: 11bdc4a815bd1e264d0ccbf42ca56f76e6ab1bbc
- go1.16.7
- FreeBSD 13.0-RELEASE

**Comment by aeneasr** [comment] 2021-09-04 15:24
Unfortunately I don’t use FreeBSD and do not know how to resolve it. It looks oike a deep dependency within dockertest. I fear there’s nothing I can do on our end here, sorry!

If you know how to fix it, please supply a PR!

**Comment by hrefhref** [comment] 2021-09-04 17:08
Sadly I don’t know a single thing about docker or go. Is there just a way to disable « dockertest » ?

**Comment by aeneasr** [comment] 2021-09-05 05:51
It’s actually only used in test but Go is notorious for compiling everything, including tests, when building binaries :/

**Comment by hrefhref** [comment] 2021-09-05 15:43
oof. So the only possible option is to fix docker test compilation, even if there's zero chance of Docker working in freebsd ?

**Comment by aeneasr** [comment] 2021-09-05 16:13
It's just the compilation which is broken, Docker is only needed to run tests - but yeah, the compile needs to be fixed first.

**Comment by joh-ku** [comment] 2021-11-27 18:53
I can confirm that bug/feature and would like to add my thoughts here.

I think this issues shows that you violate your own [design principles](https://www.12factor.net/).
Quite apart from this, docker is a deployment strategy. It has nothing to do with the product itself. Making it a dependency of your build process, even if it is only a test in this case, is bad architecture. If you'd like to provide and support a docker based deployment that's perfectly fine. But it should be isolated from the product itself.
Ory Kratos is written in Go, hence it should compile best possible on any platform that comes with a Go compiler – and so does FreeBSD.

**Comment by aeneasr** [comment] 2021-11-27 22:45
Did you actually read the thread? It’s quite frustrating to see people comment on year old issues in a rude tone with obvious misunderstanding of the underlying issue. Open source maintainers are stretched thin and under constant barrage. Why not provide positive feedback and helpful discussion instead of flaming and shitting on projects with wrong assumptions? Unbelievable how fucking stupid this can get.

**Comment by michael-o** [comment] 2021-11-28 11:18
@ory seriuously? So there is nothing else around Linux for you? The world seems to be flat these days.

**Comment by NickUfer** [comment] 2021-11-28 13:34
@michael-o I don't know if you get it but the problem was how your colleague communicated his points.

**Comment by michael-o** [comment] 2021-11-28 13:58
> @michael-o I don't know if you get it but the problem was how your colleague communicated his points. Next time a bit less passive aggressive and more constructive should to the trick.

He sharply pointed out that your approach is unnecessarily platform specific and violates your own goals. I have such comments many times taken as a personal attack although he's trying to tell you that the world isn't flat.

**Comment by aeneasr** [comment] 2021-11-28 14:12
I overreacted because I found the tone very rude and the points made are incorrect, clearly indicating that the poster has no idea how the software works. I have reverted the actions and am looking forward to useful and constructive ideas to resolve build issues on FreeBSD. Please be nice in open source projects, this project in particular is only maintained by me and I have little patience for trolls.

**Comment by michael-o** [comment] 2021-11-28 14:28
> I overreacted (and am sorry for that) because I found the tone very rude and the points made are incorrect, clearly indicating that the poster has no idea how the software works. I have reverted the actions and am looking forward to useful and constructive ideas to resolve build issues on FreeBSD. Please be nice in open source projects, this project in particular is only maintained by me and I have little patience for trolls.

Reacting properly to harsh criticism is a virtue. Hard to achieve, granted.

**Comment by michael-o** [comment] 2021-11-28 15:02
There are two ways at it: You are doing a good job, but we can make it better OR you are doing a shifty job, why can't you do it right. I prefer to interpret @joh-ku's comment explicitly as the former.

Personally for as a developer I feel great when I know that my code runs on many platforms identically and makes millions happy.
PS: I am biased because I do Maven releases and the above is true.

**Comment by joh-ku** [comment] 2021-11-28 16:24
@aeneasr The way you reacted to my comment is completely inappropriate and, in contrast to my (perhaps to harsh) technical input, it was without any doubt a rude attack against my person (I resist to post its content here). This is simply unprofessional, no matter if we are in OSS or commercial space or anywhere else.
If you felt in any way offended by my words I'd like to point out that this for sure was not my intention, so sorry for that.

But let's return to the content:

> He sharply pointed out that your approach is unnecessarily platform specific and violates your own goals.

Exactly this is my point. This is not trolling. It's about portability. Nobody commented on this so far.

> I overreacted (and am sorry for that) because I found the tone very rude and the points made are incorrect, clearly indicating that the poster has no idea how the software works.

May I ask you to explain why my points are incorrect?

**Comment by aeneasr** [comment] 2021-11-28 16:35
The fix is most likely resolvable via:

1. Identifying the dependency causing the build issue on FreeBSD
2. Updating the dependency using go mod replace if there is a fix for the dependency available
3. If not make a PR at the dependency resolving the issue
4. If none of the above are an option, write a replacement for said dependency

As stated before, due to the way we bootstrap tests for easy consumption, it is not possible nor desirable to strip Dockertest from the project.

And as with all open source project, collaboration is key! If this is a problem you encounter, you’re in the best position to fix it! Maintainers including myself are happy to help wherever possible

**Comment by aeneasr** [comment] 2021-11-28 16:38
> If you felt in any way offended by my words I'd like to point out that this for sure was not my intention, so sorry for that.

Apology accepted, I hope you accept mine too :)

**Comment by joh-ku** [comment] 2021-11-28 17:21
> Apology accepted, I hope you accept mine too :) My remarks were out of line and indeed unprofessional.

Accepted as well. :) I'm well aware that OSS maintenance is not an easy task and I highly appreciate your work.

I think, as already pointed out by others, the main problem is that FreeBSD does not support docker. If an encapsulation of business logic and deployment is not desired we probably are somewhat stuck at this point. I just think that this is not an ideal solution portability-wise like we can see from this issue (and therefore against my understanding of your design principles) – and please let me emphasize again, that I don't want to offend anybody with that statement. It's solely a technical note.

**Comment by aeneasr** [comment] 2021-11-28 17:30
I see - so Docker ist not needed to run, it’s merely a tool to bootstrap tests! I think the problem is some incorrect syscall value in some dep that causes the build failure! :)

**Comment by michael-o** [comment] 2021-11-28 18:11
Regardless of the fact that this is some Docker module:
```
../../go/pkg/mod/github.com/ory/dockertest/v3@v3.6.5/docker/pkg/system/mknod.go:12:19: cannot use dev (type int) as type uint64 in argument to unix.Mknod
```
and it should be skipped for non-Linux in most cases the underlying C/OS call isn't portable because the struct you are trying to read has either different types or members.

Definition of `dev_t` on FreeBSD: https://github.com/freebsd/freebsd-src/blob/373ffc62c158e52cde86a5b934ab4a51307f9f2e/sys/sys/_types.h#L113: `uint64_t`
Definiton of `dev_t` on Linux:  https://elixir.bootlin.com/linux/latest/source/include/linux/types.h#L13: `uint32_t`.
Well, this isn't going to work.

Here: https://github.com/ory/dockertest/blob/44efd604a6887f5f132e2f076307f3a1ddf471ff/docker/pkg/system/mknod.go#L11-L13

You like need to take the largest available type here. I don't know how platform-specific code is done in Go, obviously not ifdefs.
BUT since this is `dockertest` it does not make any sense to port it since Docker a whole uses Linux-only features. It should be skipped in the build by OS detection.

Note: I have never written Go, but ported many OSS to FreeBSD and HP-UX, found many non-portable pitfalls down the road.

**Closed** 2021-11-28 18:11 UTC

**Comment by aeneasr** [comment] 2021-11-28 18:13
You're right :) All that was needed was to add a FreeBSD version of the mkdir file, which, when using freebsd was expecting an uint instead of an int as on other platforms (mac, windows, linux). So added a file to deal with the type conversion for freebsd, afaik building works now!

**Comment by michael-o** [comment] 2021-11-28 18:19
> You're right :) All that was needed was to add a FreeBSD version of the mkdir file, which, when using freebsd was expecting an uint instead of an int as on other platforms (mac, windows, linux). So added a file to deal with the type conversion for freebsd, afaik building works now!

Hopefully it won't suffer from any truncation because you pass in `func Mknod` and int. And Go's `Mkdev` will propertly map to FreeBSD's `makedev(int, int)`.

**Comment by joh-ku** [comment] 2021-11-28 18:51
Build works now! Thank you @aeneasr and @michael-o :)

The remaining problem with the Makefile (as bash defaults to `/usr/local/bin/bash`)

```
# GO111MODULE=on gmake install
gmake: /bin/bash: No such file or directory
```

can probably be fixed by replacing

```
SHELL=/bin/bash -o pipefail
```

with

```
SHELL=bash -o pipefail
```

as you export `PATH` anyway.
