### ISSUE TITLE
Kratos v0.5.4-alpha.1 docker compose problems

### ISSUE THREAD

**Issue by hrstoyanov** [ory/kratos#846] opened 2020-11-22 23:38 UTC
**Describe the bug**

Creating a simple dev environment with Docker compose, Kratos and Postgres is a real pain! 
The reason is that Postgres is know to be hard to detect when ready to accept db request on tcp port 5432 and this trips Kratos. For example, the below docker compose file does not work, because Kratos attempts to connect to Postgres which is not ready yet. And notice that the use of **depends on** is of no help and misleading:

```
version: '3.8'

services:
  kratos:
    image: oryd/kratos:v0.5.4-alpha.1
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    depends_on:
      - postgresd
    command:
        serve -c /etc/config/kratos/kratos.yml --dev
    environment:
      - DSN=postgres://kratos:secret@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    networks:
      - intranet

  postgresd:
    image: postgres:13.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
    networks:
      - intranet

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - intranet

networks:
    intranet:
```

**Reproducing the bug**

_Server logs_

**Expected behavior**

Kratos should document a way to set up Postgres dev environment quickly and painlessly.

**Environment**

- Version: Kratos v0.5.4-alpha.1
- Environment: MacOS, Docker latest

**Additional context**

This is a well know, nasty issue with Postgres, workarounds are suggested [here](https://stackoverflow.com/questions/35069027/docker-wait-for-postgresql-to-be-running). Basically, the Kratos container can implement a trivial shell wait cycle and only launch once Postgres port 5432 is open:
```
...
    command:
        /bin/ash -c 'while !</dev/tcp/db/5432; do sleep 1; done; serve -c /etc/config/kratos/kratos.yml --dev'
```
Unfortunately, this is not possible, because the Kratos alpine image was built without **/bin/ash**   shell (or any shell really!), unlike the classic Alpine image:
```
docker run -it oryd/kratos:v0.5.4-alpha.1 /bin/ash
Error: unknown command "/bin/ash" for "kratos"
Run 'kratos --help' for usage.
unknown command "/bin/ash" for "kratos"
 docker run -it alpine /bin/ash
/ # 
```
Here are possible solutions I see:
- Just add the /bin/ash shell to the Kratos image, document the wait trick for Postgres users.
- People can burn their own docker image with /bin/ash added, but why?
- [I use this] Separate out the Postgres container into another docker compose or run it in Docker straight. Run Kratos and Postgres independently, waiting for Postgres to become available. Pretty ugly!
- Implement some wait capability in Kratos to depend on port (or wait fixed time). This is just for this Postgres workaround ...

**Comment by itsgitz** [comment] 2020-11-23 02:15
I got same issue while using Kratos with Postgres.

**Comment by zepatrik** [comment] 2020-11-23 09:18
Did you see our quickstart docker compose files in the root of the repo? They use a migration container that has
```yaml
restart: on-failure
```
set and therefore retries connecting until it succeeds.

https://github.com/ory/kratos/blob/master/quickstart.yml#L20

**Comment by hrstoyanov** [comment] 2020-11-23 17:33
@zepatrik this is even more confusing, because:
- for a brand new development , migration part should not be necessary, so I removed it.
- the two compose file you mentioned: **quickstart.yml** and **quickstart-postgres.yml** refer to different databases (sqllite and postgress) and also start a quickstart demo app, which I do not need.

Also, I expected to see Kratos creating tables in Postgres upon first start, but did not see any? Is this what the "migration" is supposed to do, and if so, it should be renamed to "initial seeding" or something less confusing to developers.


Can you please explain/document what is necessary to get a "clean Postgres environment" docker compose environment for development.

**Comment by aeneasr** [comment] 2020-11-23 17:47
> for a brand new development , migration part should not be necessary, so I removed it.

That is an incorrect assumption, it is required.

**Comment by hrstoyanov** [comment] 2020-11-23 19:41
@aeneasr maybe "migation" should be renamed to "seeding" to avoid future confusions

**Comment by zepatrik** [comment] 2020-11-23 20:46
Well, you have to run it on every update that changes the database schema. If we add some way that auto-migrates your database, and it has a bug, it could potentially break all of your production data irreparably. That's why you always have to do this manually and test in a staging environment before applying to production.
Regarding the docker compose files, have a look at https://docs.docker.com/compose/extends/
You will see that the sqlite settings are overwritten by the postgres specific values. I recommend you start off with the quickstart and replace the sample app with your own as soon as you got it working the official way.

**Comment by hrstoyanov** [comment] 2020-11-23 23:11
@zepatrik thanks ... I was hoping Kratos would use internally something like [FlyDB](https://flywaydb.org/), but will work with what  you have. Not sure about the status of this issue, close if you think so. Maybe improve the documentation a bit?

**Comment by aeneasr** [comment] 2020-11-24 07:14
We use a migration process but every migration can have bugs or behave differently on different versions of different database types (pg, mysql) in different contexts (data amount, ...). The way we do it is considered best practice for large scale and production envs.

We can definitely improve the docs though. What would you write and where? :)

**Comment by aeneasr** [comment] 2020-12-08 19:32
I am closing this because it is not a bug. If you still have suggestions for the docs please let us know!

**Closed by aeneasr** 2020-12-08 19:32 UTC
