### ISSUE TITLE
MySQL migration to v0.8 fails 

### ISSUE THREAD

**Issue by seremenko-wish** [ory/kratos#2167] opened 2022-01-21 01:43 UTC
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Applying migration `20210817181232000006_unique_credentials.mysql.up.sql` fails due to the wrong order of commands. SQL query in file `20210817181232000004_unique_credentials.mysql.up.sql` creates a foreign key that blocks query in file `20210817181232000006_unique_credentials.mysql.up.sql` which fails with an error:

```
An error occurred while connecting to SQL: error executing migrations/sql/20210817181232000006_unique_credentials.mysql.up.sql, sql: ALTER TABLE `identity_credential_identifiers` MODIFY `identity_credential_type_id` char(36) NOT NULL;: Error 1832: Cannot change column 'identity_credential_type_id': used in a foreign key constraint 'identity_credential_identifiers_type_id_fk_idx'
```

Change column type in fizz (https://github.com/ory/kratos/blob/master/persistence/sql/migrations/templates/20210817181232_unique_credentials.up.fizz#L30)  should be applied before adding the foreign key https://github.com/ory/kratos/blob/master/persistence/sql/migrations/templates/20210817181232_unique_credentials.up.fizz#L21

MySQL version: 5.7.12

### Reproducing the bug

Just run `kratos migrate sql` on empty DB

### Relevant log output

```
DEBU[2022-01-20T18:01:35-08:00] > unique_credentials                          audience=application service_name=Ory Kratos service_version=master
DEBU[2022-01-20T18:01:35-08:00] Migration has not been applied but it might be a legacy migration, investigating.  audience=application service_name=Ory Kratos service_version=master version=20210817181232000006
DEBU[2022-01-20T18:01:35-08:00] Migration has not yet been applied, running migration.  audience=application service_name=Ory Kratos service_version=master version=20210817181232000006
DEBU[2022-01-20T18:01:35-08:00] 1.5043 minutes                                audience=application service_name=Ory Kratos service_version=master
An error occurred while connecting to SQL: error executing migrations/sql/20210817181232000006_unique_credentials.mysql.up.sql, sql: ALTER TABLE `identity_credential_identifiers` MODIFY `identity_credential_type_id` char(36) NOT NULL;: Error 1832: Cannot change column 'identity_credential_type_id': used in a foreign key constraint 'identity_credential_identifiers_type_id_fk_idx'
```

### Version

v0.7.1

### On which operating system are you observing this issue?

Linux

**Comment by aeneasr** [comment] 2022-01-21 08:21
Tnank you! We run migrations against MySQL (I believe 5.7) continuously against an empty (e2e tests) as well es partially populated (see migratest module). Do you have any idea why they pass there but not for you?

**Comment by seremenko-wish** [comment] 2022-01-21 19:22
The reason why it works in your DB is that you don't have `FOREIGN_KEY_CHECKS=1` set in your DB by default, which is not a production-like environment. In real prod DB, this should always be on.

**Comment by seremenko-wish** [comment] 2022-01-21 19:33
The issue a actually much larger than just DB migrations. After I apply a workaround related to foreign key checks, Kratos flows fail with different issues related to foreign key checks. This is an example of failing registration flow:

```
| time=2022-01-21T19:27:33Z level=debug msg=Running PostRegistrationPrePersistHooks. audience=application flow_method=password  ...    
                                                                                                                                             │
│ time=2022-01-21T19:27:33Z level=info msg=Encountered self-service flow error. audience=audit error=map[message:mysql create: Error 1452: Cannot add or update a child row: a foreign key constraint fails (`wish_accounts_dev_kratos`.`identity_credential_identifiers`, CONSTRAINT `identity_c │
│ redential_identifiers_type_id_fk_idx` FOREIGN KEY (`identity_credential_type_id`) REFERENCES `identity_crede)] http_request=m ...

│ time=2022-01-21T19:27:33Z level=error msg=An error occurred and is being forwarded to the error user interface. audience=application error=map[message:mysql create: Error 1452: Cannot add or update a child row: a foreign key constraint fails (`wish_accounts_dev_kratos`.`identity_credent │
│ ial_identifiers`, CONSTRAINT `identity_credential_identifiers_type_id_fk_idx` FOREIGN KEY (`identity_credential_type_id`) REFERENCES `identity_crede)] http_request=...

```

**Comment by aeneasr** [comment] 2022-01-21 20:47
That is very strange, we run all e2e tests against MySQL in default configuration (no extra settings)

Could you maybe provide a fully reproducible set up?

It’s also possible that we use MySQL 8.0 in the CI which might handle this differently

**Comment by aeneasr** [comment] 2022-01-22 09:13
Our CI uses MySQL 5.7 for integration, migration, and e2e tests: https://github.com/ory/kratos/blob/d9c82173a1926e815dbb3528cf0c1595d976e84c/.circleci/config.yml#L36-L38

**Comment by seremenko-wish** [comment] 2022-01-27 19:14
#2044 is definitely related to this problem.

I finally found the root cause of the issue. And it is SQL_MODE system variable (https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_sql_mode). I stumble upon this setting on a bug report https://bugs.mysql.com/bug.php?id=93838 (check response `[17 Apr 2019 19:09] Dmitry Lenev`) 

If I run the migration with `sql_mode=TRADITIONAL`, it works well. Apparently, empty sql-mode SQL connection setting means different modes for AWS RDS and MySQL 5.7 image from Docker Hub. `TRADITIONAL` mode seems stricter in general, and at the same time allows column type conversion from NULL to not NULL. It would be nice to include explicit sql_mode option for MySQL connection.

**Comment by aeneasr** [comment] 2022-02-25 13:35
Closing as a dupe of #2044

**Closed by aeneasr** 2022-02-25 13:35 UTC
Labels: bug

**Comment by williamohara** [comment] 2022-06-22 04:17
hi @seremenko-wish and @aeneasr i am getting the exact same issue using Azure Database for MySQL ... Looking at https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_sql_mode - it does not list "traditional" as a valid value. What to do?

**Comment by williamohara** [comment] 2022-06-22 04:36
> hi @seremenko-wish and @aeneasr i am getting the exact same issue using Azure Database for MySQL ... Looking at https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_sql_mode - it does not list "traditional" as a valid value. What to do?

NM - i read more - TRADITIONAL is equivalent to STRICT_TRANS_TABLES, STRICT_ALL_TABLES, NO_ZERO_IN_DATE, NO_ZERO_DATE, ERROR_FOR_DIVISION_BY_ZERO, and NO_ENGINE_SUBSTITUTION - I just set all of them for SQL_MODE and it worked
