### ISSUE TITLE
Mysql Migration Err.

### ISSUE THREAD

**Issue by chungyan5** [ory/kratos#364] opened 2020-04-26 07:21 UTC
**During kratos-migrate, i got this err.**
docker logs --tail 30 kratos_kratos-migrate_1
```
An error occurred planning migrations: CREATE TABLE `schema_migration` (
`version` VARCHAR (14) NOT NULL
) ENGINE=InnoDB;
CREATE UNIQUE INDEX `schema_migration_version_idx` ON `schema_migration` (`version`);: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE UNIQUE INDEX `schema_migration_version_idx` ON `schema_migration` (`versi' at line 4
```

**Reproducing the bug**

- git clone https://github.com/ory/kratos.git
- i removed some non-matching configuration file item at contrib/quickstart/kratos/email-password/.kratos.yml
```
-    after:
-      password:
-        hooks:
-          -
-            hook: session
-          -
-            hook: verify
```

- edit the quickstart-mysql.yml
```
 services:
   kratos-migrate:
     environment:
-      - DSN=mysql://root:secret@tcp(mysqld:3306)/mysql?max_conns=20&max_idle_conns=4
+      - DSN=mysql://root:secret@tcp(mysqld:3306)/mysql

   kratos:
     environment:
-      - DSN=mysql://root:secret@tcp(mysqld:3306)/mysql?max_conns=20&max_idle_conns=4
+      - DSN=mysql://root:secret@tcp(mysqld:3306)/mysql

   mysqld:
     image: mysql:5.7
@@ -15,3 +15,5 @@ services:
       - "3306:3306"
     environment:
       - MYSQL_ROOT_PASSWORD=secret
+    networks:
+      - intranet
```

- edit the quickstart-mysql.yml
```
   kratos-migrate:
-    image: oryd/kratos:latest-sqlite
+    image: oryd/kratos
     environment:
       - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
     volumes:
@@ -33,7 +33,7 @@ services:
   kratos:
     depends_on:
       - kratos-migrate
-    image: oryd/kratos:latest-sqlite
+    image: oryd/kratos
     ports:
```

- docker-compose -f quickstart.yml -f quickstart-mysql.yml up -d

**Comment by aeneasr** [comment] 2020-04-26 09:30
Did you build the `oryd/kratos` yourself?

**Comment by chungyan5** [comment] 2020-04-26 13:16
hi Aeneasr, 

Do you mean this command for rebuild "docker-compose -f quickstart.yml -f quickstart-mysql.yml up -d --build --force-recreate" ?

I tried, but same err. I have not seen any Dockerfile? so it should directly downloaded the image fr. quickstart.yml 
```
...
image: oryd/kratos:c1204da74d12
...
```
Not build from Dockerfile.

**Comment by aeneasr** [comment] 2020-04-27 15:44
Thank you, I'm currently writing e2e tests so the error should surface there and then I'll fix it!

**Comment by aeneasr** [comment] 2020-04-29 12:57
I can't reproduce this on master. We did however find some issues with the clocks/times in MySQL which we'll fix. I'd suggest to wait for the next release to check out MySQL!

I'm therefore closing this :)

**Comment by aeneasr** [comment] 2020-04-30 12:35
It reappeared in the CI: https://circleci.com/gh/ory/kratos/3565?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by aeneasr** [comment] 2020-04-30 13:10
Figured it out - you need to add `?multiStatements=true` to the connection string. I'll fix that!

**Comment by zepatrik** [comment] 2020-05-01 14:18
fixed by https://github.com/ory/kratos/pull/374

**Closed by zepatrik** 2020-05-01 14:18 UTC
