### ISSUE TITLE
Send emails via an api instead of smtp

### ISSUE THREAD

**Issue by ederuiter** [ory/kratos#2139] opened 2022-01-12 16:46 UTC
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Currently all mails are sent out via courier and, as far as I could find, courier only supports smtp/smtps.
For normal email sending most mail providers like sendinblue/sendgrid still provide an smtp interface, however the preferred way is via their api.

Using their api would allow also us to use more advanced features like transaction email templates.

Our usecase would be sending all emails via sendinblue so we can use their transactional mail templates (which can be edited/maintained by non-developers)

### Describe your ideal solution

It seems https://github.com/ory/kratos/pull/1941 already lays the foundation, but only applies for sending sms.
This would need to be extended to also allow sending mails via an api.

- [ ] add support for http/https protocol in `courier.smtp.connection_uri`
- [ ] add `courier.smtp.request_config` (similar to `courier.sms.request_config`)

^ although it might better to rename `courier.smtp` to `courier.mail` or introduce a new `courier.api` option

### Workarounds or alternatives

It might be possible to use webhooks for this, but that would require a whole lot of extra configuration per flow + would not be as robust.

### Version

0.8

**Comment by zepatrik** [comment] 2022-02-03 09:06
I think this is a duplicate of https://github.com/ory/kratos/issues/1030
Feel free to add to that issue

**Closed by zepatrik** 2022-02-03 09:06 UTC
Labels: feat
