### ISSUE TITLE
Goland (JetBrains) does not recognize `leak_sensitive_values` in `config.yml`

### ISSUE THREAD

**Issue by frederikhors** [ory/kratos#1714] opened 2021-09-02 16:38 UTC
**Describe the bug**

Goland (JetBrains) does not recognize `leak_sensitive_values` in `config.yml` both for `Kratos` and `Oathkeeper`.

**Reproducing the bug**

Open the project in Goland or Jetbrains (or VSCode I think).

See screenshot below.

_Server configuration_

```yaml
...
log:
  level: debug
  leak_sensitive_values: true
...
```

![image](https://user-images.githubusercontent.com/41120635/131883178-a3a9007f-4040-48f0-b8ed-97cc4e629965.png)

**Comment by aeneasr** [comment] 2021-09-04 05:43
Probably an issue with the config json schema @zepatrik

**Comment by zepatrik** [comment] 2021-09-06 08:24
Did you set a version? The version in the config currently is only used to allow IDEs to map the right schema :wink:

**Comment by frederikhors** [comment] 2021-09-06 10:44
> Did you set a version?

Yep! And nothing...

![image](https://user-images.githubusercontent.com/41120635/132205415-66ecb930-a0b9-48fa-a1ff-b82dfc930650.png)

**Comment by aeneasr** [comment] 2021-09-06 11:49
Looks like you’re in the wrong repo? That’s Oathkeeper and Oathkeeper doesn’t support that config yet

**Comment by frederikhors** [comment] 2021-09-06 14:55
Isn't this the configuration I need to follow? Do you see the version here? https://www.ory.sh//oathkeeper/docs/reference/configuration

**Comment by zepatrik** [comment] 2021-09-06 15:01
I see, it is an error in the schema store. I will fix that, but until now ignore the errors.

**Comment by zepatrik** [comment] 2021-09-06 15:05
For context: https://github.com/SchemaStore/schemastore/pull/1297 broke some of our URLs, including Hydra.

**Comment by zepatrik** [comment] 2021-09-17 13:30
Closing because I could not reproduce this with Kratos. Oathkeeper does not support `leak_sensitive_values`, but will fix the docs for it.

**Closed by zepatrik** 2021-09-17 13:30 UTC
