### ISSUE TITLE
Feature Request: Have access to username in email templates

### ISSUE THREAD

**Issue by Quasarman** [ory/kratos#925] opened 2020-12-18 17:05 UTC
**Is your feature request related to a problem? Please describe.**

Not really a problem but it would be nice to address the user, who just registered, in the verification email with their username and not a generic "Hi", something like "Hello {{ .username }}, nice to....".

**Describe the solution you'd like**

Having access to the traits defined in the identity schema inside the email templates (atleat those not confidential)

**Describe alternatives you've considered**

A generic "Hi," at the start of the email

**Additional context**

None.

**Comment by aeneasr** [comment] 2020-12-18 17:06
Yes, absolutely - this is kind of a dupe of: https://github.com/ory/kratos/issues/834#issuecomment-745334333

But will track it as an individual issue nonetheless

**Comment by Quasarman** [comment] 2020-12-18 17:14
Awesome! I Didn't see that there is already a ticket open for this. Thanks for the blazing fast reply.

**Closed** 2021-11-04 13:08 UTC
Labels: bug, corp/m5
