### ISSUE TITLE
All emails are sent multiple times  if kratos deployed with multiple instances over 1 DB

### ISSUE THREAD

**Issue by pavlovmike** [ory/kratos#732] opened 2020-10-02 15:06 UTC
**Describe the bug**

Activation and recovery emails are sent as many times as Kratos instances are up 

**Reproducing the bug**

1. Deploy Postgres DB
2. Deploy 2(or N) instances of Kratos with common Db connection (in our case - it's just scaled instances in Kubernetes)
3. Let user register and email with the same activation link will be delivered to mail-box in N copies

**Expected behavior**

E-Mail courier module should block each email record in Db before sending and not allow another Kratos instance to take this email for processing

**Environment**
- Version: v0.4.6

**Comment by aeneasr** [comment] 2020-10-02 15:44
Potential dupe of https://github.com/ory/kratos/issues/402#issuecomment-658367245

**Closed** 2020-10-14 10:30 UTC
