### ISSUE TITLE
Cockroach migrations failing with >v20.1.0

### ISSUE THREAD

**Issue by zepatrik** [ory/kratos#1017] opened 2021-01-26 11:56 UTC
As reported in the [slack](https://ory-community.slack.com/archives/C012RJ2MQ1H/p1611629656040100) there seem to be some issues in the migrations related to schema changes. @tricky42 what version do you use and did you have any issues?

@christian-roggia

**Comment by aeneasr** [comment] 2021-01-26 12:15
This is fixed on master

**Closed** 2021-01-26 12:15 UTC
Labels: bug

**Comment by sw8fbar** [comment] 2021-01-27 01:15
Hi, could you please tell me which docker image will have this fix ?

**Comment by aeneasr** [comment] 2021-01-28 14:51
Simply run `make docker` in the project's root. Be aware that there might be bugs and other problems.

**Comment by sw8fbar** [comment] 2021-01-29 05:06
Thank you.

**Comment by PetrSilar** [comment] 2021-02-19 15:18
Since I'm not able to access slack mentioned above, I'd like to ask if the issue is this:
```
An error occurred while connecting to SQL: error executing github.com/ory/kratos:/persistence/sql/migrations/sql/20200812124254_add_session_token.cockroach.up.sql, sql: DELETE FROM sessions;
ALTER TABLE "sessions" ADD COLUMN "token" VARCHAR (32);COMMIT TRANSACTION;BEGIN TRANSACTION;
ALTER TABLE "sessions" RENAME COLUMN "token" TO "_token_tmp";COMMIT TRANSACTION;BEGIN TRANSACTION;
ALTER TABLE "sessions" ADD COLUMN "token" VARCHAR (32);COMMIT TRANSACTION;BEGIN TRANSACTION;
UPDATE "sessions" SET "token" = "_token_tmp";COMMIT TRANSACTION;BEGIN TRANSACTION;
ALTER TABLE "sessions" DROP COLUMN "_token_tmp";COMMIT TRANSACTION;BEGIN TRANSACTION;
CREATE UNIQUE INDEX "sessions_token_uq_idx" ON "sessions" (token);COMMIT TRANSACTION;BEGIN TRANSACTION;
CREATE INDEX "sessions_token_idx" ON "sessions" (token);COMMIT TRANSACTION;BEGIN TRANSACTION;: ERROR: unimplemented: schema change statement cannot follow a statement that has written in the same transaction (SQLSTATE 0A000)
```
If so, is there some way to fix it by patching published docker image or something other then building kratos from master?
Or is there release schedule?

Thank you

**Comment by aeneasr** [comment] 2021-02-19 15:27
This is fixed on master!

**Comment by kwypchlo** [comment] 2021-03-11 16:38
Any plans on releasing a new version with this commit any time soon?

**Comment by aeneasr** [comment] 2021-03-12 11:59
We planned on publishing an in-between release of ory kratos before MFA lands but abandoned that plan as work on MFA has continued and is expected not to take as long as we feared. Sorry for the inconveniences!
